### ISSUE TITLE
Scaling tab of Radial Chart under self-managed display not working

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#10]
Error short description/title: Scaling tab of Radial Chart under self-managed display not working
Date found: 12/1/2020
IFs Version (number, VB6/.NET, Install/Development): IFs 7.56 .NET install
Person found by: Suraj Thapa
Type of error (see below): Display issues
Description of error: The scaling tab of Radial Chart (which is under self-managed display) is not working. Steps to replicate the error, if applicable: Using Pardee wiki - link – do as it says about "Radial Chart" for self-managed display –

Go to Self-Managed display. 2. Select country/regions, any three variable (I chose GOVINDSECUR, GOVINDCAPAC, and GOVINDINCLUS), and just base working model, then go to display 3. Go to Graph Tab and then to the "Radial Chart" 4. Go to scaling and try "on" 6. We do not see it normalizing to 1. (In "IFs with Pardee 7_60.NET Dic 18 2020", it does not change to "on" at all.)
Attempt to recreate error in VB6 or .NET depending on where found and note whether error reproducible: It was on windows and .NET

**Comment by PardeeCenterIFs** [comment]
José: Thank you Suraj, this one is the same problem as the previous one (issue #15 ), I have now fixed it, and it should work fine in version 7.63
