### ISSUE TITLE
Change to land use code; brazil/indonesian forest

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#102]
We currently have an issue with grazing land projections in brazil, relative to other global models.

![image](https://user-images.githubusercontent.com/18350553/138322944-042c1c9b-3b54-4423-84aa-a25c9cf129cf.png)

The issue is a simple fix. We currently have an exemption for how we project grazing land in brazil. If we exclude that code, projections are much improved.

'If RegName$(R%) = "Brazil" Then
        '    If GDPPCP(R%) < 35 Then lddev = 0.005 * LDI(R%, Graz)
        '    If GDPPCP(R%) < 25 Then lddev = 0.01 * LDI(R%, Graz)
        'End If
        'If RegName$(R%) = "Indonesia" Then
        '    If GDPPCP(R%) < 35 Then
        '        lddev = 0.015 * LDI(R%, Graz)
        '    ElseIf GDPPCP(R%) < 45 Then
        '        lddev = 0.0075 * LDI(R%, Graz)
        '    Else
        '        lddev = 0
        '    End If
        'End If

@PardeeCenterIFs @jose for the next release could we simply code these lines out, and that's it.
If we have done that the issue can be closed.

**Comment by PardeeCenterIFs** [comment]
I have commented out that code, and the change will be included in version 7.79 (not in the Beta)
