### ISSUE TITLE
Timor-Leste Economy 

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#110]
Description: When looking at the interest rate and exchange rate, Timor-Leste appears irregular. Interest rates go to 0 for a decade while the savings are already in the red (debt). 
Date Found: 10/13/2021
IFs Version: 7.77
Found by: Resource Team

![image](https://user-images.githubusercontent.com/83729959/138517157-281ca032-1da2-4d95-bde2-f120624ed38e.png)

![image](https://user-images.githubusercontent.com/83729959/138517182-d7239389-3840-4aa8-9322-7989c9c72867.png)

**Comment by PardeeCenterIFs** [comment]
Interest rates no longer go to 0 in version 7.86, althoug exchange rates looks similar than before.

![image](https://user-images.githubusercontent.com/33665510/175134402-016aa1b3-dfc8-43e3-8cf7-2617309aa07e.png)

**Comment by PardeeCenterIFs** [comment]
Exchange Rates look different in version 8.23, I don't think this is an issue anymore.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/8abc2b09-de42-4885-897f-f17fa473b68a)
