### ISSUE TITLE
Additional CLPCCV forecast functions

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#114]
We are exploring alternative forecast equations for CLPCCV. Please add a switch that would allow us to shift between our current analytical function (which should remain our Base-run default) and three new table functions (all bivariate power relationships). 

Attached are the Tablfunc entries for the following 3 relationships:
1. Coef. of Variance versus GDP per Capita at PPP (Power) (Median)
2. Coef. of Variance versus GDP per Capita at PPP (Power) (Optimistic)
3. Coef. of Variance versus GDP per Capita at PPP (Power) (Pessimistic)

[TablFunc_AltCLPCCV.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/7412449/TablFunc_AltCLPCCV.zip)

**Comment by PardeeCenterIFs** [comment]
We can use clpccvr, we can do:

0 is already current function, else is constant, so we could do 1 = constant, 2 = median, 3 = optimistic and 4 pessimitic.

**Comment by PardeeCenterIFs** [comment]
This was implemented, and it will be included in version 7.82
