### ISSUE TITLE
Importing Groups bug

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#116]
When you import groups through Extended Features you get a bug that I think is related to Core and Not-Core groups.  It's a non-fatal error (you can still import the groups) but it's a bug.

[VarListTransmission.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/7429167/VarListTransmission.zip)

**Comment by PardeeCenterIFs** [comment]
Dave created this issue with priority 5, and with an extra issue related to not being able to use the new groups right away, so I tackled this one, and it will be included in version 7.79, or maybe recreating 7.78

https://github.com/PardeeCenterDU/IFs-Issues-Tracking/issues/115
