### ISSUE TITLE
Country Name "Slovakia" Appears in Excluded Country

### ISSUE THREAD

**Issue by tzhang852** [PardeeCenterDU/IFs-Issues-Tracking#117]
1. Country Name "Slovakia" Appears in Excluded Country
2. Date Found: 10/27/2021
3. IFs Version: 7.78
4. Found by: Tiffany Zhang
5. Error Type: Data Error
6. Raw Data contains country name "Slovakia". When reading into IFs, "Slovakia" is excluded from the data even though it exists as spelled in the data.
7. Branch: Production
![image](https://user-images.githubusercontent.com/18152676/139195497-950a9bd3-69ee-4ad4-8897-f4b1b8f89cbd.png)
![image](https://user-images.githubusercontent.com/18152676/139195513-4fa0f035-76a6-4549-b353-5362acaa5b96.png)
![Slovakiaissue](https://user-images.githubusercontent.com/18152676/139195623-764b05d9-7563-40e3-9471-14ec6d0efc85.JPG)

**Comment by quciet** [comment]
I've talked with @tzhang852 and this is not an issue in IFs.

Because we haven't added a new IFs country column in the Country Translation table, so she will be using Slovak Republic instead of Slovakia.

 So I'm going to close this issue
