### ISSUE TITLE
Discrepancy between population growth and popr

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#119]
Issue identified in both 7.75 and confirmed in 7.78. 

We have popr in the flex display displaying population growth, and used in several areas of the code

We also have population per year.

In theory popr= popyear(t)/popyear(t-1)

but it currently does not. We need to understand the order of calculations, and whether we are actually calculating population and popr correctly.
changes to popr will perpetuate through because it is used in several areas of the code. we should check the forward effects of these corrections

Assigned priority 3 cause the population routine is quite important, but could be lowered if it is purely a display and not a code issue

**Comment by PardeeCenterIFs** [comment]
This issue was addressed and fixed in #118
