### ISSUE TITLE
Search box in flex display and self-managed doesn't populate chosen variable

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#12]
Date found: 1/28/2021
IFs Version: 7.62 dotNet
Found by: Kaylin McNeil
Error Type: Missing features

Description: When you go to search in both flex display and self-managed and search for a variable...when you select a variable and click 'Load,' you are returned to the flex display/self-managed page but the variable you chose doesn't load.

Steps to Replicate: For example, in either flex display or self-managed...

click search
search for eg. 'education'
click on an education variable, eg. EDPRICR
click 'Load'
[nothing happens, you are returned to self-managed or flex display but the education variable isn't chosen]
Reproducible in VB6 (Y/N): No, this functionality works in VB6

**Comment by PardeeCenterIFs** [comment]
JRS: It worked on my version, in Self-managed, it returns ready to select the country, in flex displays it returns with the list already selected.
