### ISSUE TITLE
IFs .NET - Drivers not loading in self-managed

### ISSUE THREAD

**Issue by markmeziere** [PardeeCenterDU/IFs-Issues-Tracking#123]
Within self-managed on the IFs Online version when you select any variable or parameter and then click on it within the table that populates you are presented with a number of options. Clicking on "Drivers" loads a blank screen.

Date found: 11/2/2021

![image](https://user-images.githubusercontent.com/84362289/139960850-099ab4de-f961-4163-965a-f5fa99a49401.png)

Screen that loads:

![image](https://user-images.githubusercontent.com/84362289/139960894-8423ef79-c8d5-47d9-98a3-aff28d319fdc.png)

**Comment by PardeeCenterIFs** [comment]
Ok, I see there is a problem with the old Nevron control, I remember it had a complicated license, which was for a single server, it is possible that when we migrated to our new server earlier this year, we lost this functionality, but it's not easy to get it back, I'm thinking that this month when we update the web version, we will be updating the GUI too, and moving away from the old Nevron control to what we use for the asp.net stand alone version, which is a highchart networkgraph, so this we'll be fix hopefully in less than a month as we're hopping to update before December 2nd 2021.

**Comment by PardeeCenterIFs** [comment]
This problem is now fixed in version 7.79, which is now in the online version.
