### ISSUE TITLE
Expand the core group toggle in IFsinit to cover any other forms that have a "core group" toggle

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#124]

**Comment by PardeeCenterIFs** [comment]
I don't think we currently have a GroupFiltering option being saved in IFsInit.mdb, we only have it for Filtering FlexDisplays lists, which is different (DefaultFlexDisplayFilter).

Also I think we only have "Group Filtering" in 2 forms: Flex Displays and the Group Creation form.

**Comment by Coryv221** [comment]
Was implemented a few weeks ago, closing now
