### ISSUE TITLE
Adding abs change to flexible display

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#126]
Hi there,

this is not an issue, rather it is a suggestion. Currently, in the table function under the flexible display, I can click Display Options to get percent changes through the years for a country. Can we add an option so that I can check the actual value change instead of percentages?

Thanks,
Yutang

**Comment by quciet** [comment]
I moved this up to priority 4, since #64 was discussed today in the modeling pod meeting.

**Comment by quciet** [comment]
After the discussion, we are now thinking about how to add a reference year to do the comparison. 

For example, if I want to see the percentage change or absolute change based on year 2019, 2024, ... (any year in the table instead of just the base year).

**Comment by Coryv221** [comment]
A beta version of the feature is made and now being tested by the Documentation team. Barring any issues coming up, this should be included in the next Consolidation or two!

**Comment by quciet** [comment]
Much appreciated!!!

**Comment by Coryv221** [comment]
Should be in 7.83 and ready for use once sent out
