### ISSUE TITLE
Malnpopsw

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#128]
We would want to set the malnpoppsw to IFs standard to 1, i.e. using the clpccv forecasts. currently this is set to zero.
I believe we had discussed this before, and even had an issue on it. But I could not retrieve it.

Should be a small update.
New malnpop code has been extensively tested

**Comment by PardeeCenterIFs** [comment]
I inteded to do this change back in August, but I made a mistake, so the change didn't take, but not it should work, this should be included in version 7.82
