### ISSUE TITLE
Growth Accounting

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#13]
Date found: 1/30/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features
Description: Error occurs
Steps to Replicate: Display>Specialized Displays for Issues> Growth Accounting
Reproducible in VB6 (Y/N): No, this functionality works in VB6

![image](https://user-images.githubusercontent.com/64621297/110177775-b5134b00-7dc2-11eb-808c-7f1b66e4deb3.png)

**Comment by PardeeCenterIFs** [comment]
JRS: Thank you for finding this Barbara, I think I got it, and the fix should be included in version 7.63.
