### ISSUE TITLE
Electricity population wo access (flex display infrastructure physical)

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#134]
There's some weird stuff happening with Electricity population without access in group aggregations for urban, rural, and total. 

Right now (7.81) it says that 296 million people lack access to electricity in urban areas.  But if you take the urban population (around 4.5 billion) and the share of the population with electricity (96%) the total population without electricity is 180 million, not 296 million.  

Same is true for urban and rural.

I remember there were aggregation issues with this during the infrastructure volume, but this is pretty wild in terms of how different the results are.

**Comment by PardeeCenterIFs** [comment]
I see the problem, we're always using total population in the formula, so this display is only right if you select total, not for urban or rural, you would need to change the formula for each dimension, something we can't easily do, I guess the easiest would be to create 3 variable lists one for urban, rural and total.

An alternative would be to create a new variable named POPBYAREA or something like that, with 2 dimensions, like we have for INFRAELECACC, using those 2 variables in a formula would be fine in a Flex Display, but the current will not work for Urban or Rural:

A*(1-B/100)
A = POP
B = INFRAELECACC

**Comment by PardeeCenterIFs** [comment]
I have now created a new varlist, and it's showing 157 Million people with no access in urban areas. I have removed the existing list and added the attached and those changes will be included in version 7.82.

[VarListTransmissionElectricityNOAccByArea.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/7832038/VarListTransmissionElectricityNOAccByArea.zip)
.
