### ISSUE TITLE
Show Computed Functions

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#14]
Date found: 1/30/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features

Description: Data Analysis > Show Computed Functions, IFs.Net does not allow selection of Filter/cannot move forward

selecting "Extend List" or "Order by Last Change" does not change outcome

Reproducible in VB6 (Y/N): No, this functionality works in VB6, completely different functionality (graph does not populate in net version)

**Comment by PardeeCenterIFs** [comment]
JRS: This function still had the old graphic control "AnyChart", I have now updated it to use "HighChars" and it seems to be working fine. The change should be include in version 7.63.
