### ISSUE TITLE
Error in Growth Accounting Display (vb6)

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#142]
Go to the Growth Accounting Display and select Guinea, Technology Base MFP, then Graph. Try to hover over the first 2 points of the graph, and you get an error Object doesn't support this property or method.

**Comment by Coryv221** [comment]
The issue is noted, and will be moved to top of my todolist!

**Comment by Coryv221** [comment]
In "Hotfix-Issue-142" Code has been committed to fix the issue. It is ready for testing and deployment. It is pulled directly off Main, so merging will not implement any other changes, beyond the hotfix.

**Comment by PardeeCenterIFs** [comment]
I have tested it, and it's working well, it will be included in version 7.82.
