### ISSUE TITLE
Display issue; regional aggregation

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#143]
IFs 7.79

We have the display list America Central & Carribbean
However, if you look at decompose you see only African countries.
Hence, the list needs to be updated (either naming convention, or the underlying countries)

See below for a screen shot with an example

![image](https://user-images.githubusercontent.com/18350553/151149323-2bbceab2-fe81-4530-ab3a-a550308fc6d0.png)

**Comment by Coryv221** [comment]
Barbara has update the group to have the correct nations and will be included in the next consolidation of IFs.
