### ISSUE TITLE
Error message: Malnourished people history and forecast

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#144]
IFs 7.79

When trying to load malnourished people, history and forecast. Error message pops up stating that series is missing from datadict.mb
We are likely referring to the wrong dataseries, that was updated in the food security project

I put it at level 3 since we will have a new project on food security pretty soon, and need this feature to work to explore data

See below for screenshot of error message

![image](https://user-images.githubusercontent.com/18350553/151149911-96ed506f-04c4-4f29-833b-d9a8e4695aaa.png)

**Comment by PardeeCenterIFs** [comment]
Got it, I had missed updating the historic analog of MALNPOPP , now using SeriesMalnPop% consistent with preprocessor.
This fix will be included in version 7.82.
