### ISSUE TITLE
Bar Chart with a single year

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#147]
Bar chart should work with a single year, right? It does not seem to. It gives an error message. Then it produces a mis-labelled plot.

![image](https://user-images.githubusercontent.com/53452620/151915979-e367729e-59a5-4ed4-a847-dd114802e967.png)

![image](https://user-images.githubusercontent.com/53452620/151916017-2680e6b2-f9bb-4f56-8153-c31ff704eff3.png)

**Comment by PardeeCenterIFs** [comment]
Cory, I think this might be related to the work we did on Advancing years to a multiple of 5, I vaguely remember some of the vetting images showing single columns that look odd.

**Comment by Coryv221** [comment]
I agree, I think it should be next on my list to clear, bar charts not being able to show single year data seems like a fairly large problem to me

**Comment by PardeeCenterIFs** [comment]
This issue has been fixed by Cory, I have tested, and it looks good, it'll be included in version 7.82.
