### ISSUE TITLE
Switch to a new base year for GDP constant price

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#148]
We wanted to move our current base year from 2011 constant price to a more recent year, especially a year that is being used by WDI so that our data are comparable (2015 or 2017?)

This requires following steps, probably simultaneously,

1. For Yutang, 
Make sure we can transfer both preprocessors GDP2011 & GDP2011PCPPP to a recent year without problems. 

2. For José
Make sure changes that need to be made in the code are identified (perhaps there aren't any).

3. For someone else?
The change will increase the value for GDP at MER and GDP PC at PPP due to inflation. There should be serious vetting of the model and estimation functions!

**Comment by PardeeCenterIFs** [comment]
I think simply doing a global replace in the code of SeriesGDP2011 with either SeriesGDP or SeriesGDP2017 should do it, and cover also SeriesGDP2011PCPPP.

Now we currently have variable GDPPCP2005, should we keep it? or remove it and add GDPPCP2011?

Yutang, I suppose that once we migrate to say SeriesGDP2017 there will be a large subset of existing series that will need to be updated, anything that has US$ as units, I assume.

**Comment by PardeeCenterIFs** [comment]
List of issues to consider:

1. Code changes (simply global replace of SeriesGDP2011 with the new SeriesGDP), check poverty, check health.
2. Adding or renaming poverty variables, new level in 2017 $?
3. Removing GDPPCP2005 and replace it with GDPPCP2011 or simply add the latter.
4. List of Series, currently in US$ as units, to consider migration.
5. Discuss Revising functions created with 2011$ and 2005$?

**Comment by quciet** [comment]
> I think simply doing a global replace in the code of SeriesGDP2011 with either SeriesGDP or SeriesGDP2017 should do it, and cover also SeriesGDP2011PCPPP.
> 
> Now we currently have variable GDPPCP2005, should we keep it? or remove it and add GDPPCP2011?
> 
> Yutang, I suppose that once we migrate to say SeriesGDP2017 there will be a large subset of existing series that will need to be updated, anything that has US$ as units, I assume.

Following steps for the data team,
1. Check preprocessor series that will be affected by this price change (hopefully that we already changed everything to % of GDP)
2. Do we want to keep a current price GDP series in the model? I know the series is already in IFsHistSeries

**Comment by PardeeCenterIFs** [comment]
On point 2. Yes, I think it would be useful to keep a curent price GDP series, specially since it's already there.

**Comment by PardeeCenterIFs** [comment]
1. Code changes are done, and will be included in version 7.91, now we have an option in ifsInit to switch the year: ConstantDollarsYear.

**Comment by PardeeCenterIFs** [comment]
2. Added new variables, need to:
       2.1 Update forward linkages
       2.2 add poverty gap and poverty line
       2.3 update poverty by age and sex

**Comment by PardeeCenterIFs** [comment]
Completed step 2.

Step 3 will be left for latter.

**Comment by PardeeCenterIFs** [comment]
For step 4. I have found this list of 9 tables:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/solox/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/solox/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



AgCropExportValueFAOTrade
AgCropImportValueFAOTrade
AgFishExportValueFAOTrade
AgFishImportValueFAOTrade
AgMeatExportValueFAOTrade
AgMeatImportValueFAOTrade
MilExpendStock
PovLineNationalWB
Xdebt



</body>

</html>

**Comment by PardeeCenterIFs** [comment]
For step 5, these are the MFP related functions to change (23 functions, 7 are for History only):

(H- 0 to 40)
GDP/Capita (PPP) Versus Govt Exp Educ as % of GDP (1960) - log
(0 to 40)
GDP/Capita (PPP) Versus Govt Exp Educ as % of GDP (2002) - log
(H- 0 to 40)
GDP/Capita (PPP) Versus Govt Exp Hlth as % of GDP (1990) - log
(0 to 40)
GDP/Capita (PPP) Versus Govt Exp Hlth as % of GDP (2000) - log
(H- 0 to 40)
GDP/Capita (PPP) Versus R&D Total  as % of GNI (1980) - linear
(0 to 40)
GDP/Capita (PPP 2005) Versus R&D Total  as % of GDP (2009) Linear
(H)
GDP/Capita (PPP) Versus Years of Educ at 15+ (1960)
GDP/Capita (PPP 2005) Versus Years of Educ at 15+ (2010) Log
(H)
GDP/Capita (PPP) Versus Life Expectancy (1970)
GDP/Capita (PPP) Versus Life Expectancy (2000)
(H)
GDP/Capita (PPP 2005) Versus Stunting (2005) Log
GDP/Capita (PPP 2005) Versus Stunting (2006) Log
(H)
GDP/Capita (PPP) Versus Freedom -Logged and Inverted (Earliest)
Freedom (Inverted) with GDPPCP and EdYears 15 (2012)

Economic Freedom (2010)
Governance Effectiveness (2005)
GOVCORRUPTversus GDPPCP, DEMOCPOLITY, GEM, Ex Export Depend (2010)
GDP/Capita (PPP) Versus Infrastructure Index Traditional (2010) Log
GDP/Capita (PPP) Versus Infrastructure Index Traditional (2100) Log
(usado 2 veces en ifsEco fuera de ifsECOMFP)
GDP/Capita (PPP) Versus Cobb-Douglas Alpha (GTAP 5)
GDP/Capita (PPP) Versus Internet Percent Use (2000)

GDP/Capita (PPP 2011) Versus Informal Share of GDP (" & CStr(BaseYear) & ") Log
GDP/Capita (PPP 2011) Versus Shadow Economy Share of Total(" & CStr(BaseYear) & ") Log

**Comment by PardeeCenterIFs** [comment]
The functions have not been updated, maybe for later with lower priority, but historic analogs and variable lists were checked for version 8.03.
