### ISSUE TITLE
Problem with Bar Graphs

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#149]
Go to Flex Displays, select Births, and 4 countries, like Afghanistan, Barbados, Chad, Djibouti. Bar Chart.

Look how Afghanistan's first bar doesn't match the data:

![image](https://user-images.githubusercontent.com/33665510/153623824-c64f68b0-1ede-4e53-9c48-5c39ee849573.png)

![image](https://user-images.githubusercontent.com/33665510/153623950-93a93705-68d7-40c6-b817-c01a49de1d95.png)

**Comment by Coryv221** [comment]
I can't reproduce this. When following the selection shown I get the following:

![image](https://user-images.githubusercontent.com/64621297/154320768-fdcbab2d-f900-4e23-8f20-0a8bbe60bd48.png)

	BIRTHS[0]	BIRTHS[0]	BIRTHS[0]	BIRTHS[0]
	Afghanistan	Barbados	Chad	Djibouti
	Mil People	Mil People	Mil People	Mil People
Year	Working	Working	Working	Working
 2017	          1.176	          .0031	           .636	          .0208
 2018	          1.187	          .0031	           .653	          .0208
 2019	          1.204	          .0031	           .671	          .0208
 2020	          1.234	          .0031	           .693	          .0210
 2021	          1.271	          .0031	           .718	          .0212
 2022	          1.311	          .0031	           .744	          .0214
 2023	          1.349	          .0030	           .769	          .0215
 2024	          1.385	          .0030	           .794	          .0215
 2025	          1.419	          .0030	           .818	          .0215
 2026	          1.448	          .0030	           .841	          .0215
 2027	          1.472	          .0030	           .863	          .0214
 2028	          1.494	          .0030	           .885	          .0212
 2029	          1.514	          .0030	           .906	          .0211
 2030	          1.531	          .0030	           .925	          .0209
 2031	          1.546	          .0030	           .944	          .0208
 2032	          1.558	          .0029	           .962	          .0206
 2033	          1.567	          .0029	           .976	          .0204
 2034	          1.573	          .0029	            .99	          .0203
 2035	          1.578	          .0029	          1.003	          .0202
 2036	           1.58	          .0028	          1.015	          .0200
 2037	          1.582	          .0028	          1.027	          .0200
 2038	           1.58	          .0028	          1.038	          .0198
 2039	          1.577	          .0027	          1.048	          .0197
 2040	          1.575	          .0027	          1.059	          .0196
 2041	          1.572	          .0027	          1.069	          .0196
 2042	          1.569	          .0027	          1.079	          .0196
 2043	          1.567	          .0026	          1.088	          .0195
 2044	          1.564	          .0026	          1.098	          .0194
 2045	          1.562	          .0026	          1.107	          .0194
 2046	           1.56	          .0026	          1.116	          .0194
 2047	          1.558	          .0025	          1.125	          .0193
 2048	          1.556	          .0025	          1.133	          .0193
 2049	          1.554	          .0025	          1.141	          .0192
 2050	          1.552	          .0025	          1.148	          .0191

**Comment by Coryv221** [comment]
I am on the most recent version that included the "first year hot fix" for issue 147: https://github.com/PardeeCenterDU/IFs-Issues-Tracking/issues/147

Perhaps that change also addressed this problem?

**Comment by Coryv221** [comment]
Nevermind, there is an issue occuring and I figured out the steps for reproducing. I am working on it now
