### ISSUE TITLE
Bar Chart Group by Geography

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#150]
Go to Flex Displays, select Births, and 4 countries, like Afghanistan, Barbados, Chad, Djibouti. Bar Chart. In the Graph form click on the menu: Display Format/Group by Location. 

![image](https://user-images.githubusercontent.com/33665510/153624715-0198ce19-064d-458c-959e-2ac32d8f9502.png)

I think this was working before, but not sure what changed.

**Comment by Coryv221** [comment]
Issue is fixed in VB6. The feature is not in .NET, and an issue was created to log that request.
