### ISSUE TITLE
Readability concerns for some y-axis unit conversions in line graphs

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#152]
When selecting an individual country to show percentage of popualtion on AIDS Death Rate I get the following graph:

![image](https://user-images.githubusercontent.com/64621297/154324217-00cbfabe-f01b-4e0e-aca1-ccd44a4b2a00.png)

When selecting multiple countries I get this instead:

![image](https://user-images.githubusercontent.com/64621297/154324286-ab4a9e72-c251-4304-88a5-2a450904d961.png)

However, for percent of GDP coming from Cyber Benefit with a single country I get the correct graph:

![image](https://user-images.githubusercontent.com/64621297/154324666-22e13724-1a3b-4e79-80d2-8cb2fbc3a2b2.png)

This correct result occurs when multiple countries are selected:

![image](https://user-images.githubusercontent.com/64621297/154326833-1e6824f6-9235-4496-9276-79060b1db28c.png)

But then when I select AIDS Deaths in millions for a single country I get: 
![image](https://user-images.githubusercontent.com/64621297/154324897-e3bcb6b6-ae1e-4d0f-9596-e27f97a432c3.png)

And the same is true for multiple countries:
![image](https://user-images.githubusercontent.com/64621297/154325018-25171c55-d66d-4e7d-b0ac-6b328a9d2ddd.png)

The Deaths in millions issue is odd to me because mu (µ) is the correct metric conversion for values this small in millions, but we are then not actually displaying the unit in a way that is an intuitive reading of the unit we are promising (in millions of people). If a reader doesn't know what mu represents in this context, it could come across as there is a major error in the way the data is plotted (it took me a bit to realize this just meant 400 deaths and not 400 million deaths because I didn't notice the mu conversion) I recognize it is technically correct, but not intuitive for a reader (who I don't think would know the metric conversion for a base value to 10^-6 is represented as mu).

This issue has two items I then want to change (pending a discussion at modeling pod):

1. there is an issue with how some percentages are being converted, and this is a bug that has to be fixed
2. I would like to change how low "millions of {unit}" values are shown to just be a .0004 value(in this case) or when this conversion is selected by our algorithim as "best" we give the user the ability to select whether they want a conversion to mu (which means they have been given fair warning to what the impact will be for the visualization) or as .0004.

**Comment by Coryv221** [comment]
After re-reading some details on how metric conversions are notated, the "m" in the togo map is not because the percentage conversion was wrong, but instead that we converted it to "milli" percentages.

I have the same issue with readability on this (especially since "m" is frequently used to mean "millions" not "millis") and think that should incde a warning as well. 

Along with that, we should do a change to include the measurment type in the axis in general (such as adding a "%" symbol) when we are displaying data as percentages. For example, changing "1.0m" -> "1.0m%" or "1.0%(m)" if we do the unit conversion.

**Comment by PardeeCenterIFs** [comment]
This is no longer an issue with .NET
