### ISSUE TITLE
Flex display swaping United States with Uruguay when data are then displayed

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#153]
When selecting United States of America in flex displays:
![image](https://user-images.githubusercontent.com/64621297/154328555-062961a1-c073-4c26-a4b4-99cd3331d1f9.png)

then selecting graph or table I get data from Uruguay:
![image](https://user-images.githubusercontent.com/64621297/154328588-bd4933ef-3d8d-4bcd-b82c-7a345def4dcf.png)

Then the exact opposite occurs when I select Uruguay. I then get United States of America data. When going to United Kingdom (the next acending neighbor) or Uzbekistan (the next descending neighbor) there is no swapping and the value is correct. This occurs on all variables, regardless of the number of dimensions, and what dimensions are selected.

**Comment by PardeeCenterIFs** [comment]
Got it Cory, Aliases got messed up when we standarized region names, back in version 7.66, and now that you're making the default we see the problem.

The fix for both the current Aliases, and for the renaming of regions, that originated the problem will be included in version 7.83.
