### ISSUE TITLE
Initial Year Values for Dependence, Bandwidth, and Influence Not Matching Data

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#156]
The initial year values of dependence, bandwidth, and influence should be set to the value in their respective series per the end of the first year normalization block of code.

As an example case, actor United States partner Mexico (the US-Mexico dyad) may be useful as a test. In this case, the values for each in 2017 in a 7.82 install version are:

- Dependence: Model - 0.209; Data - approx 0.667
- Bandwidth: Model - 0.178; Data - approx 0.633
- Influence: Model - 0.065; Data - approx 0.740

IFs Version: 7.82 Install

**Comment by caleb-petry** [comment]
My apologies; I thought I added this as a comment on Friday. This issue may be even more related to #162. 

I tried to recreate this issue in my dirty (non-fixes related to the migration work rolled back) 7.80 dev version with a web GUI. The initial year is recorded at the correct values in that version, but no values past 2017 are saved. 

Other dyadic variables appear to be working as intended. 

-----------------------------------------------------------------

Fixing the .NET issue has a higher priority (the current issue thread could be lowered in priority if considered a separate issue) if seen in a more recent version.

**Comment by PardeeCenterIFs** [comment]
We were using GDS before it was computed in the calculation of DEPENDENCE, this is the new code (simply using sgds intead of GDS in future years):

'jrs 2022/02/21
                        If IY > 1 Then
                            arms_import_stock_milstock(i, j, 1) = DYADMILMSTOCK(i, j) / 1000000000 / sgds(j, Mil) * 100 'jrs 2020/07/10 added / 1000000000
                        Else
                            arms_import_stock_milstock(i, j, 1) = DYADMILMSTOCK(i, j) / 1000000000 / GDS(j, Mil) * 100 'jrs 2020/07/10 added / 1000000000
                        End If
