### ISSUE TITLE
World Bank Financial Flows

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#16]
Date found: 2/1/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features

Description: all zero values, in every scenario from 2016-onward
Steps to replicate: Select any country> World Bank Financial Flows> all zero values across in every scenario from 2016-onward, I chose Mexico, Malawi, and Kenya to test

Reproducible in VB6 (Y/N): No, this functionality works in VB6, at least some values displayed from 2016 onward in the scenarios included in the dotNet version

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce in version 7.65
