### ISSUE TITLE
Age of Marriage Project

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#164]
We'd like to have the age of marriage dimensioned by country and gender, and initialized first with the WB data, filled in with the UN data, and finally any missing data can be filled with a bivariate function with GDP per capita (PPP). 

Steps:

1. Add the new variable in ifsVar.mdb.
2. Rebuild Common so that pointers already consider this new variable.
3.  Initialize new variable with data from WB, UN.
4. Find a regression between new variable and GDPPCP with the intent of filling holes.
5. If new data is empty after trying to initalize with both sources of data, then using new regression to fill holes.
6. Start the conversation on drivers for the long term forecast.

**Comment by mtirfan66** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6964653/

**Comment by PardeeCenterIFs** [comment]
We have now implemented a basic forecast with GDPPCP and EDYRS15(Total) as drivers.

![image](https://user-images.githubusercontent.com/33665510/158466462-9ea8d842-6221-4c83-a340-dda30a77b1fc.png)

Discussing responsiveness to GDPPCP in countries like Libya.

![image](https://user-images.githubusercontent.com/33665510/158466697-0289e951-99c8-4930-a609-bac734b778a5.png)
