### ISSUE TITLE
.NET SSP Batch Run

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#166]
7.82--Scenario Analysis, Batch, World Integrated, SSPs, 2100.  In Chrome.

Received this error: 

   Error in Scneario: Conversion from string "Democratic Republic of" to type 'Single' is not valid.

          Run Number:    3 of 5 

          Year of Run:

**Comment by PardeeCenterIFs** [comment]
The problem was that the .sce file had an error, It's not:

Congo ,Democratic Republic of

but instead:

Congo, Dem. Republic of the

Fixing that in SSP3Final.sce, SSP4Final.sce and SSP5Final.sce should fix the problem.
