### ISSUE TITLE
NET IFs link to the homepage

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#169]
The link under the IFs Home button needs to be updated

![image](https://user-images.githubusercontent.com/34465524/158452772-08720f2e-f495-40d8-ba30-baac86aa1746.png)

Currently, it is directing to the old home page we had 

![image](https://user-images.githubusercontent.com/34465524/158452891-67266826-8188-4fb5-a02e-622bc735a9fa.png)

Thank you!!!

**Comment by PardeeCenterIFs** [comment]
Thank you Yutang, I had already fixed it in the installation version, but had not moved the fix the web server, but I have updated the server now, so this is fixed.

Thanks again for reporting.
