### ISSUE TITLE
Country Translation Table

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#170]
Our country translation table is not being used now, and students are doing country concordance outside IFs prior to the data import process through IFs interface.

In the current data import process, people have to specify a data source and IFs will use the country translation table to find the related country names. This is not flexible enough. In addition, we will have to add a new column to the country translation table whenever there is a new source with at least one country name that is different than all previous sources. On contrast, we will just need to add one row (one more alias) to the long format of country translation table. 

For instance, you can see all the duplicated entries in the current country translation table, 

![image](https://user-images.githubusercontent.com/34465524/158698654-bcb5305b-e423-476a-bb3b-5581779682c3.png)

A long format of the table would solve this,

![image](https://user-images.githubusercontent.com/34465524/158698805-c0ee7497-24fe-473a-865e-e7bc224f5f00.png)

My proposed idea is to add an alternative approach in which people don’t specify data source, and the import process will search all entries in the long format of country translation table and find the related country name used by IFs. 

We can further improve this approach by adding a learning process to the system where people can add aliases to the country translation table (both long and wide format) through the interface of the data import process in their local machine. This is low priorty, we can discuss it in the future. 

Thanks,
Yutang

**Comment by mtirfan66** [comment]
Yutang and all,
This project was discussed way back. I am not sure why it stopped. I was told not to do anything on it. I am happy to see it back.
I already discussed with at least one of us who use this feature to pull their own data when the data team is too busy to get back to us right away. I'd talk to Jose about how much time investment he thinks is justified on the VB6 version of the data pull.
Based on those feedbacks, I'll come up with my plan on how to incorporate the improvements you are suggesting.
Meanwhile, I don't see any reason people in the data team would not be able to continue to use this feature to add/update data from known sources like WDI, UNESCO, FAO etc. Please let me know if your team would like me to conduct a training for the process.
Thank you.

**Comment by PardeeCenterIFs** [comment]
This is already implemented in .NET.
