### ISSUE TITLE
Saving scenarios in .net

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#176]
Hi all:

When I save a working file in the .NET version it doesn't save as a new .run file that I can access in Flex Display.  So, if I save a working file it shows up in Flex Display as "working file with components from (whatever I saved the file as)".  It means that I can't easily make scenarios and save them to compare.

**Comment by PardeeCenterIFs** [comment]
Yes, it does save it as a new .run.db file, it's only that the last one only shows up in Flex Displays as your working, next time you restart the model (maybe with IIS, or after 20 minutes of inactivity) you'll see it down the list in Flex Displays. Also if you save a second scenario, I think the first one should already show up in the Flex Display list, and the latest will be your working, but in any case they are being saved as new files in RUNFILES.

**Comment by PardeeCenterIFs** [comment]
I found the problem, and now the newly saved file will be showing even if it's the same as the working file. This fix will be included in version 7.85.
