### ISSUE TITLE
Batch Run not showing files in Flex Display for VB.Net

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#177]
[CCSt0.0Sq2.222.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8353735/CCSt0.0Sq2.222.zip)

I place the attached sce files in the scenarios folder in .net (7.82) and run them using batch run.  They don't populate the scenarios space in Flex Display.  They run correctly but there's nothing you can do with them.

**Comment by PardeeCenterIFs** [comment]
I'll take a look at why it's populating Flex Displays, but I'm sure that if you restart IIS (which shouldn't be necessary) they will show up.

**Comment by PardeeCenterIFs** [comment]
For a second I thought I couldn't see them in Flex displays, I went to Self-managed and they were there, then come back to Flex Displays and they were there.

**Comment by PardeeCenterIFs** [comment]
I found the problem, and fix it, the status of the newly added runfiles was not being set. The fix will be included in version 7.85.
