### ISSUE TITLE
wtempadd parameter not working (I think!)

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#178]
I increased wtempadd to try to exogenously increase global temperature and got some really weird results.  I ran it to 2100 but the model only shows results through 2050.  It also doesn't actually increase the temperature in the way you would expect.  See below for the sce file and a screenshot of WTEMP:

HIGH0000,climeconimpsw,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
CUSTOM,wtempadd,0,.07,.14,.21,.28,.35,.42,.49,.56,.63,.7,.77,.84,.91,.98,1.05,1.12,1.19,1.26,1.33,1.4,1.47,1.54,1.61,1.68,1.75,1.82,1.89,1.96,2.03,2.1,2.17,2.24,2.31,2.38,2.45,2.52,2.59,2.66,2.73,2.8,2.87,2.94,3.01,3.08,3.15,3.22,3.29,3.36,3.43,3.5,3.57,3.64,3.71,3.78,3.85,3.92,3.99,4.06,4.13,4.2,4.27,4.34,4.41,4.48,4
.55,4.62,4.69,4.76,4.83,4.9,4.97,5.04,5.11,5.18,5.25,5.32,5.39,5.46,5.53,5.6,5.67,5.74,5.81
COMMENT,START

[wtemp.docx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8354274/wtemp.docx)

**Comment by PardeeCenterIFs** [comment]
I don't see any problems, although I did got a weird message the first time I tried pasting the wtempadd values into working.sce.

![image](https://user-images.githubusercontent.com/33665510/160717881-21a59597-8fa8-4b4a-bc93-cf89d65348ca.png)

[Working.Sce.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8375389/Working.Sce.txt)
