### ISSUE TITLE
Exogenous Gini Series Not Working in VB6

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#179]
Here's the problem (and the importance of the files):  I am trying to exogenously use the gini, gdp and population files to create long-term poverty projections for the climate/poverty work.  It isn't "taking" the gini files.  Attached to the email are the sce files I'm using as well as an updated IFs.var file with the exogenous series modified.  It should all work.  But it doesn't (see the screenshot in that folder for an example).  SSP4, for example, should increase inequality significantly.

[SSPs and Inequality.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8354298/SSPs.and.Inequality.zip)

**Comment by PardeeCenterIFs** [comment]
GINIDOM was only implemented 2 days ago, to be included in version 7.84.
