### ISSUE TITLE
Development Profile

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#18]
Date found: 2/1/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features

Description: development profiles do not load
Steps to replicate: Select any country> development profile, I tested Canada, United States, China, Samoa

Reproducible in VB6 (Y/N): No, this functionality works in VB6

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce in version 7.65
