### ISSUE TITLE
Portuguese translation (scenario menu)

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#180]
In the portuguese version of Ifs the scenario analysis display is slightly different and would need to be updated.
In a standard scenario analysis form there is base, high and low option for each scenario parameter.
In the portuguese version there is only a base, and two times a "medium" and "medium"
This would need to be updated.
See screen shot below for an example with TFR

![Screenshot_IFsScenario](https://user-images.githubusercontent.com/18350553/160442727-a422cb33-7aca-443f-9c27-cb3a9cee8b25.jpg)

**Comment by PardeeCenterIFs** [comment]
I have now fixed this problem, it was an issue related to using arrays in vb6, so the 3 options had the same name, I added an index field in the ifs.FormControlCaption table, so that we can distinguish each. The fix will be included in version 7.85.
