### ISSUE TITLE
Bilateral Interaction with Gravity - Tables Unable to Scroll

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#183]
I am having an issue where I cannot scroll the tables in the bilateral interaction with gravity display and the sliders are missing. This is not an intermittent issue like some of the others have been. I also tried using the center click scroll, but that did not work either. This is a low-priority issue for me right now as I typically pull them into Excel when I need to take a closer look, but we will need this addressed by early/mid-June. My GUI is not updated to 7.82, so that might be contributing if it functions as intended in someone else's model.

![image](https://user-images.githubusercontent.com/7695597/161590547-8df2f5cf-d8b5-4821-8506-9913d6be2e98.png)

IFs Version: 7.82 VB.Net dev version with Influence changes

**Comment by PardeeCenterIFs** [comment]
Jaime has fixed this issue, and it will be included in version 7.86.
