### ISSUE TITLE
Unable to run .NET IFs despite full download

### ISSUE THREAD

**Issue by tzhang852** [PardeeCenterDU/IFs-Issues-Tracking#185]
Downloaded and installed .NET but when double clicking application, gives me Server Error in '/' Application.
4/7/2022
.NET 7.83
Tiffany
.NET Problem, New Issue?
Downloaded .NET but application won't open.
![image](https://user-images.githubusercontent.com/18152676/162279529-f3b06fbb-1fd2-4418-bbe9-ab7471e828e7.png)

Will try redownloading.

**Comment by Coryv221** [comment]
Can you post a picture of what your IFs directory looks like?

**Comment by tzhang852** [comment]
![image](https://user-images.githubusercontent.com/18152676/162285358-bdcbb150-b260-487f-bdc5-89bda81bb480.png)

**Comment by PardeeCenterIFs** [comment]
Can you also post a picture of how your IIS looks like, expanding branches as in the example below from my machine:

![image](https://user-images.githubusercontent.com/33665510/162547132-ca6cdd17-57ec-496a-80c4-4a3016fa90b4.png)

**Comment by tzhang852** [comment]
Hmm mine doesn't seem to have ifs there - will delete and do a clean install.
![image](https://user-images.githubusercontent.com/18152676/162553394-bd9c37d9-1c50-4d64-99c0-709305f256c9.png)

**Comment by tzhang852** [comment]
Clean install fixed the issue. Had to turn off Antivirus and Firewalls (Norton 360) in order for the files to be fully installed. 
![image](https://user-images.githubusercontent.com/18152676/162554487-241d9642-a8f4-4c05-a9b1-2d37e39be1f2.png)

**Comment by PardeeCenterIFs** [comment]
I'm glad to see it's working for you, and we will take note of what you say on turning off Antivirus and Firewalls (Norton 360).
