### ISSUE TITLE
Education by Age, Sex and Level

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#19]
Date found: 2/1/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features

Description: Education by Age, Sex and Level never loads, remains on a "loading resources" spinning circle
Steps to replicate: Select any country> Education by Age, Sex and Level

Reproducible in VB6 (Y/N): No, this functionality works in VB6

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce in version 7.65
