### ISSUE TITLE
Translating "Create Variable Lists"/"Create Displays" to .NET

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#193]
Self-managed -> Select any Variables -> Variable Selection Options -> Create Variable List from Selected... (not Display Lists from...)

Self-managed -> Computations -> Create the computation -> Create Variable List from Selected....

This needs to be integrated into .NET (including the form for creating), because we know that many of the researchers utilize it

This will involve:
- Building an API to the Access files for R/W
- Creating a form for inputing and editing the lists -> this needs the ability to manage computations  (format can change, functionallity cannot)
- Creating two new nav-bar items for editing + creating lists in Self-managed
- Creating a nav-bar item for editing lists on the main-page

Phases:
1. Insert new Variable and Computation Lists
2. Delete Variable and Computation Lists
3. Edit Variable and Computation Lists

**Comment by PardeeCenterIFs** [comment]
1. Phase 1 is completed now and it will be included in version 7.86, and I have asked Cory to work in the Import and Export process before continuing to work on phase 2 and 3. The Import and Export process in vb6 is found in the Flex Display form, menu: List Features/Exchange List/Export or Import Lists.

**Comment by Coryv221** [comment]
All that's left, as of now, is importing. We are also adding a transition from Access -> SQLite file IO to complete

**Comment by Coryv221** [comment]
This is completed, and now in .NET as of a few weeks ago
