### ISSUE TITLE
.NET batch run not advancing

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#194]
Short Description: Batch run option not advancing. Hanging on Run 1, before the first year is displayed
Date found: 04/26/2022
IFs Version: IFs 7.83 .NET; on local VM (Windows 11)

![image](https://user-images.githubusercontent.com/12075041/165371814-a288b663-61dc-4785-9880-87e86117a056.png)

**Comment by PardeeCenterIFs** [comment]
Can you post here the 4 scenarios you're trying to run.

**Comment by dkbohl** [comment]
[Version 09.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8595156/Version.09.zip)

**Comment by PardeeCenterIFs** [comment]
I was able to run all 4 scenarios in a batch using version 7.84
