### ISSUE TITLE
Influence Subroutine Changes & New Parameters

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#196]
Two things here; the first is integrating changes to the influence subroutine. Attached here is a .txt file with the new version of _ifsEcoDyadicINF_. Additionally, tradeagreementindex needs to be uncommented in the declarations on line 236. The changes included here change the normalization process, cap shared IGOs at the minimum value in the dyad, and switch trade to goods only. They are indicated by "clp 2022/03/*"

[INFcode.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8574272/INFcode.txt)

For this code to work the following parameters and their initial values need to be added:

1. fbicdepmin  = 0
2. fbicdepmax = 4.133662
3. fbicbandmin = 0
4. fbicbandmax = 3.207063
5. fbicinfmin = 0
6. fbicinfmax = 0.56966
7. fbiclortotal = 372052.5
8. fbicigototal = 366000000
9. fbictradeagreetotal = 1845908
10. fbictotaltradetotal = 3039668
11. fbicalliancetotal = 12200000
12. fbicarmstocktotal = 276653.6

Additionally, we wish to add additive parameters to DYADMILMSTOCK and XDYADAID for a total of 14 new parameters.

**Comment by PardeeCenterIFs** [comment]
I have now taken your changes, and implemented the new parameters, and it will be included in version 7.84
