### ISSUE TITLE
Dyadic Aid Forecast Changes

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#197]
Following from Barry's new gross monadic aid changes, we can now bring the dyadic aid logic in line with other dyadic variables. There are three changes here:

1. Change first-year forecast
a. Initialize from data
b. Save estimated value for use in later years
c. Adjust to match monadic flows
3. Change later-years forecast
a. Calculate estimated value
b. Use change from saved estimated value from previous period to drive growth
c. Adjust to match monadic
3. Add AdjustXDyadicAid function

The equation for the new aid forecast would be:
`XAid = exp[(21.85192*POWER_Actor) + (-13.64736*POWER_Partner) + (0.000000556*GDPpppPC_Actor) + (-0.0000814*GDPpppPC_Partner)]`

If more convenient, I have the new AnalFunc entries version also.

**Comment by caleb-petry** [comment]
I forgot to mention this in the initial post, but an additive parameter would be needed and a multiplicative one could be useful.

**Comment by PardeeCenterIFs** [comment]
I have finished implementing this, and it will be included in version 7.84.
xdyadaidadd had already been implemented for issue #196 
xdyadaidm has been there for a while now, Dec. 2017
