### ISSUE TITLE
Life Expectancy in Uganda Subnational - Limited Variations in District Forecasts

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#199]
There is life expectancy data (SeriesLifExpectMale/SeriesLifeExpectFemale) for the Ugandan districts. However, there is no difference in LIFEXP (64.77 years for all) and no meaningful difference (0.05 years; 64.79 vs. 64.74 years) in LIFEEXPHLM seen across the districts. I would have expected to see more. Is this due to data challenges in other areas (for example, mortality) or the breaking out process?

Version Found: 7.83 VB6 Install Subnational Uganda with Project Data for Migration and Remittances

**Comment by PardeeCenterIFs** [comment]
Those data series (SeriesLifExpectMale/SeriesLifeExpectFemale) are no longer used in the preprocessor, we now use: SeriesLifeExpectIHMEMaleHistOnly and SeriesLifeExpectIHMEFemaleHistOnly.
Those are the ones we need to break out for Ugandan districts.

**Comment by caleb-petry** [comment]
Follow-up question, I renamed those series to SeriesLifeExpectIHMEMaleHistOnly and SeriesLifeExpectIHMEFemaleHistOnly and imported them as project data yesterday. It seems to have had no effect.

Do they need to be included during the breakout process to impact this calculation?

**Comment by PardeeCenterIFs** [comment]
Project data was originally designed to be country specific, then recently, maybe a year ago, we implemented some changes to allow importing project data for multiple countries at the same time, and I think Mohammod and I tested it, but maybe not for a case where there's 135 "Countries", maybe you can share the project file, and I can check if there's any obvious problem with it.

**Comment by PardeeCenterIFs** [comment]
From what I can see the project file has data for 2014, but the regular file has values all the way to 2016 for Uganda and most countries, so I assume when you break out Uganda, all 135 provinces get the same value for 2016, maybe also for other years, so when you import project data, you replace the values in 2014, but the one that is used is 2016.

You need to get 2016 or 2017 data for the project file

**Comment by caleb-petry** [comment]
Fixed alongside population data updates. See Modeling Pod Email Thread _Uganda version 7.83_ for files.
