### ISSUE TITLE
Sample Error (Resolved)

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#2]
Date found: 10/18/2020
IFs Version: 7.56 .NET Install
Found by: Barbara Stone
Error Type: Blowup/ Display Issue
Description: Clicking ‘Map’
Steps to Replicate:

Select Flexible Display
Select Agriculture display category
Select Agricultural Exports, Value- Billion dollars display
Select 2050 Horizon
Select IFsBase.run.mdb and C19AprGr.run.db scenarios
Selected Brazil (country region)
Selected 00-No Filter
Select fish as 2nd Dimension
Select “Map”
Error message appears (see screenshot)

Reproducible in VB6 (Y/N): No error message occurs in VB6. The error is reproducible in 7.56 .Net

**Comment by PardeeCenterIFs** [comment]
This is working now.
