### ISSUE TITLE
Bilateral Influence Forecasts: Install Version Issues .NET

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#200]
Version: .NET 7.84 Install
![image](https://user-images.githubusercontent.com/7695597/167197366-fdfdf603-9acb-4bed-8653-c43c30f9a97d.png)
![image](https://user-images.githubusercontent.com/7695597/167197400-31221c66-9e84-4132-8b28-77671a3a2974.png)
![image](https://user-images.githubusercontent.com/7695597/167197434-87c1d75c-86b2-4e73-bed6-1c2ff733298d.png)
![image](https://user-images.githubusercontent.com/7695597/168329610-ee99bb49-0344-479d-9e4b-0baf9fb05045.png)

The values appear to be initialized correctly. Dependence and Influence lack values in later years and the Bandwidth forecast differs from those seen in my Development version (shown below).

For comparison, the next two images show the graph and table for these variables in my 7.84 .NET Development version with the more expected behavior (~~The table shows null entries, but I have seen this with other repeated values near zero that are calculated correctly and show in the line graph display~~; These values are showing as nulls, they appear as zeros during the model run, maybe fine):
![image](https://user-images.githubusercontent.com/7695597/167197638-1e37d06a-96df-4f38-87cc-9e0b192e5768.png)
![image](https://user-images.githubusercontent.com/7695597/167197726-6420e1bd-d0e4-48f4-ada0-7049b3506c8a.png)

**Comment by PardeeCenterIFs** [comment]
This is what I get in the installation version of 7.84 using the newly fixed data from Yutang:

![image](https://user-images.githubusercontent.com/33665510/168909552-670ba808-542c-43fb-8700-a8e82310de90.png)

Maybe this is one that we need to keep an eye on, differences between development and installations in .NET.
