### ISSUE TITLE
Start year does not seem to persist with empirical variable plots

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#202]
The new Start Year feature with plot displays is very useful. With historical data the selection seems to be disabled once you leave the plot screen. It works okay with forecast plots. This might need a fix.
Also, is there any way we can make the option part of the flex display menu?
Is this available also for table display?

![image](https://user-images.githubusercontent.com/53452620/167923340-062140f8-6075-494d-b0bf-042884fbab1f.png)

**Comment by PardeeCenterIFs** [comment]
Cory, please switch to historical mode, you can do that in 2 ways:

1. From the Main Menu you can Open ifsBaseHist.run, which is the historical base case file.
2. From Self-Managed, there's a Menu option that says Open ifsBaseHist.

Once you've either of the 2, you can go to Flex Displays and try what Mohammod is showing us in the screen, do it for 2 different countries, and you'll see how you loose the Start Year configuration that you set for the first one.

**Comment by PardeeCenterIFs** [comment]
I don't remember fixing this, but it's working fine in version 8.23, so I'm going to close the issue.
