### ISSUE TITLE
Bilateral Influence Forecasts: Install Version Issues VB6

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#203]
Previously associated with #200, this issue relates to the initialization of FBIC in the VB6 install of 7.84.

![image](https://user-images.githubusercontent.com/7695597/168331758-73b7df34-4299-4501-bd41-47de3eb92475.png)
![image](https://user-images.githubusercontent.com/7695597/168331805-0d3a2279-9ef3-41fb-b149-0bf9d8ed505a.png)

As compared with my 7.84 .NET Dev version, the values are initialized too high for all FBIC series for the DPRK-Ukraine dyad. Different issues are seen for other dyads. This issue is mainly a placeholder for now given the current focus on .NET for the bilateral work. I will expand with more information about other observed issues in other dyads later.

**Comment by PardeeCenterIFs** [comment]
I think this is the one I reported yesterday to Yutang, where the data has a bad format for the country names, it has lots of trailing blank spaces which produces problems in vb6 for identification of the countries. Yutang said he would provide an updated version of the data file today.

**Comment by PardeeCenterIFs** [comment]
This is how it looks with  the updated/fixed data from Yutang, at least the initial point looks basically the same in both versions:

![image](https://user-images.githubusercontent.com/33665510/168884867-72f84bc1-d82c-4fed-ac17-a344c62aef81.png)
