### ISSUE TITLE
Belarus Dyadic Aid Initalization

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#205]
Belarus initializes with negative values. They receive zero aid in the monadic series but do receive aid in the dyadic. Perhaps this has something to do with it? Poland-Belarus is the worst offender. ~~While different, may be related to #204.~~

![image](https://user-images.githubusercontent.com/7695597/170528559-e55dd9bd-09f9-48ca-b6c5-d79f18a7c60c.png)

Version: 7.84 .Net development version with and without code/data changes

**Comment by PardeeCenterIFs** [comment]
Hi Yutang,

Looking into this issue I just found that there are negative values for Belarus in table SeriesAIDRec%GNI, in years 2016 and 2017, I don't think this table is supposed to have negatives, I think we now have separate tables for AIDReceipts and AID Donations, so all should be positive.

**Comment by quciet** [comment]
Hi there,

I just checked the DataDict table, both SeriesAidRec%GNI and Series AidDon%GNI are **net** ODA received or provided, 
- https://data.worldbank.org/indicator/DT.ODA.ODAT.GN.ZS?locations=BY
- https://data.worldbank.org/indicator/DC.ODA.TOTL.GN.ZS

And net Aid received can be negative, 
![image](https://user-images.githubusercontent.com/34465524/171212082-68dc12ba-e6d5-4867-8d7b-0c6d65467cdb.png)

Are you suggesting that we change the definition of these data series? 

Thanks,
Yutang

**Comment by caleb-petry** [comment]
The OECD appears to have gross ODA flows available under the _GeoBook: Geographical flows to developing countries_ option in their data viewer at stats.oecd.org.

Looking across that and other categories there it looks like net loan payments are why Belarus is negative. This one may be a tricky one to disentangle to get something more reminiscent of true gross flows.

**Comment by quciet** [comment]
> 

Thank you, Caleb! Would you mind attaching a link to the indicators you are looking at in the OECD IDS database?

**Comment by caleb-petry** [comment]
Sure! I thought the link wouldn't work, but it does seem to work: https://stats.oecd.org/Index.aspx?DataSetCode=TABLE2A.

That last bit is from looking at these series in this table:
Net ODA
Gross ODA
Net ODA Loans
Gross ODA Loans

From those, I started to get the (admittedly still quite hasty) thought that ODA loan payments might contribute to the negative net ODA for Belarus from Offical Donors. I haven't looked too much, but I didn't see any documentation that could confirm, deny, or suggest an alternative yet.

We could maybe take the gross ODA, but losing the negative net loan values would probably need to be accounted for somehow.

----------------------------------------------------------------------------------------------------------------------------------------

During the FBIC meeting, we discussed a few potential workarounds that might work for FBIC at least. That said, we probably want to figure out some way to eventually get something resembling gross aid flows.

**Comment by quciet** [comment]
Thanks! A quick comment on the negative Net ODA values, both WorldBank and OECD said this in their FAQ session, 

_When calculating net ODA, loan repayments are recorded as negative and deducted from ODA and loans. In some cases loan repayments are higher than new ODA and net ODA will show as a negative number._

So I think loan payment is indeed the key. Barry was asking if we can provide a data series for loan repayment.

**Comment by caleb-petry** [comment]
It looks like the OECD does have a loan repayment series that seems pretty easy to pull together as a monadic one. The quick version of how I pulled it up:

1. From that link above, click "Aid (ODA) disbursements to countries and regions [DAC2a]" on the left side
2. Select the _Customize_ option in the top-left of the data table; Select _Year_; Select from 1960 to latest avaliable
3. Select the _Customize_ option in the top-left of the data table; Select _Aid Type_; Deselect all, select "ODA Loan Repayments"
4. Do the same as the last two and decide on current or constant (2020 millions) prices
5. Select the _Customize_ option in the top-left of the data table; Select _Donor_; Deselect all, select "Offical Donors, Total"

That said, I am getting an error when trying to download it. If it keeps acting up for this series, I think we could do the same fairly easily by taking (if they work):

Loan Payments = Gross ODA Loans - Net ODA Loans

The main issue that I see is making sure they play well with the existing "gross" World Bank series since they might come from a different portion of the OECD's data.

**Comment by PardeeCenterIFs** [comment]
For now, we have implemented a limit on monadic AIDDON and AIDREC so that they don't go negative in the preprocessor for the initialization of bilateral AID. This fix will be included in version 7.85, and all of those negative points should now be 0s.
