### ISSUE TITLE
Unable to Scroll Bilateral Display Table in .Net Version

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#206]
I am unable to scroll when using the bilateral display table view. The middle mouse click does not work and the scroll bars are missing. This is a minor issue for me but will need to be fixed prior to public versions where the bilateral display is highlighted.

![image](https://user-images.githubusercontent.com/7695597/170547452-17aae7b6-8df6-4cce-b308-35cac6f7e0e6.png)

IFs Version: 7.84 .Net Development

**Comment by PardeeCenterIFs** [comment]
I think this is a duplicated issue, same as #183
