### ISSUE TITLE
Country Profile

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#21]
Date found: 2/1/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features

Description: Country Profile, remains on a "loading resources" spinning circle and never loads
Steps to replicate: Select any country> Country Profile

Reproducible in VB6 (Y/N): No, this functionality works in VB6

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce in version 7.65
