### ISSUE TITLE
Bilateral forecasts inoperable (cannot rebuild base)

### ISSUE THREAD

**Issue by collinmeisel** [PardeeCenterDU/IFs-Issues-Tracking#210]
IFs installation version 7.86 in VB6 and .NET does not allow users to rebuild the base with bilateral data. 

Issue found by Collin on 17 June 2022. Caleb has tried workarounds, but none have worked yet as of 22 June 2022. 

To replicate the error, install IFs on a non-virtual machine, download and move the data in the the DATA/Bilateral Folder, relink the IFs Dyadic and IFs Dyadic_FBIC series if necessary, and attempt to rebuild the base.

![Screenshot (113)](https://user-images.githubusercontent.com/60792865/175143320-698813a7-287f-4593-a5a4-346708830bc6.png)
.
This is a show-stopper for our FBIC forecasting work, which we plan to be presenting in DC on 12 July and will need working scenarios for roughly one week prior.

**Comment by PardeeCenterIFs** [comment]
There are 2 different issues in this thread:

1. The problem with rebuilding the base in vb6 and .NET in version 7.86 was addressed on June 21st, and the fix will be included in the next consolidation. In the mean time Caleb has a workaround using data files.

2. The problem with the  .NET gui in your machine, which I haven't been able to reproduce yet, sent some instructions to get a more detailed error message.

**Comment by collinmeisel** [comment]
Hi all,

The workaround that Caleb produced with a project file is good to go, thanks! It will be a day or three before I get to checking the .NET version again and trying out the instructions for a more detailed error message. Since it's not mission critical, I think we can close this issue for now, and I can open a new, more accurate issue if needed once I have a more detailed error message for .NET.

Thanks again,
Collin
