### ISSUE TITLE
VarList file not uploading country groupings correctly

### ISSUE THREAD

**Issue by katieclements** [PardeeCenterDU/IFs-Issues-Tracking#218]
The attached VarList file has the desired country groupings and correct country names in IFs, but when uploaded into IFs it does not create the correct country groupings in line with the groupings in the document. 

[VarListTransmission.UNW.Country.Groups1.mdb.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/9124181/VarListTransmission.UNW.Country.Groups1.mdb.zip)

**Comment by PardeeCenterIFs** [comment]
How was this file created?
I noticed that in table GroupingFull if you look for the row for the US, the id is incorrectly 179, when the correct value should be 178. Uruguay seems to have switched with the US, now showing 178 when it should be 179.

Is it possible this file was created when the United States of America was called USA in IFS, and that only the name was updated but not the Region Id? If that's the case that could also affect other countries.

**Comment by katieclements** [comment]
I pulled the file from IFs directly so I'm not sure why those errors would have occurred.

**Comment by katieclements** [comment]
[VarListTransmission.accdb.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/9404201/VarListTransmission.accdb.zip)
here's another version of the file that still cannot be uploaded

**Comment by PardeeCenterIFs** [comment]
I converted this to Sqlite and tested in version 8.02 and it's loading fine.
