### ISSUE TITLE
.NET blow up

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#219]
in 7.88 go to Self Managed Display and Variable Search.  I get this error.

<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="font-family: Verdana; font-weight: normal; font-size: 18pt; color: red;">Server Error in '/ifs/ifsweb' Application.<hr width="100%" size="1" color="silver"></h1><h2 style="font-family: Verdana; font-weight: normal; font-size: 14pt; color: maroon;"><i>Compilation Error</i></h2></span><span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif " style="color: rgb(0, 0, 0); font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Description:<span> </span></b>An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Compiler Error Message:<span> </span></b>BC30456: 'InitializeCulture' is not a member of 'ASP.frm_searchvar_aspx'.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Source Error:</b><br><br>

 
--
Line 1:  <%@ Reference Page="~/frm_Message.aspx" %> Line 2:  <%@ page language="vb" autoeventwireup="false" inherits="IFsWeb.frm_SearchVar, App_Web_p55tjny4" enableEventValidation="false" %> Line 3:  <%@ Register TagPrefix="cswm" Namespace="Coalesys.WebMenu" Assembly="Coalesys.WebMenu" %>

<br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Source File:</b><span> </span>C:\Users\jonathan.moyer\AppData\Local\IFs\IFsWeb\frm_SearchVar.aspx   <span> </span><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Line:</b><span> </span>1<br><br><br><div class="expandable" onclick="OnToggleTOCLevel1('compilerOutputDiv')" style="text-decoration: underline; font-weight: bold; color: navy; cursor: pointer;">Show Detailed Compiler Output:</div><br><div class="expandable" onclick="OnToggleTOCLevel1('dynamicCodeDiv')" style="text-decoration: underline; font-weight: bold; color: navy; cursor: pointer;">Show Complete Compilation Source:</div><br><br><hr width="100%" size="1" color="silver"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Version Information:</b> Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4494.0</font>
</body>
</html>

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce this one, maybe clearing your browser cache, or alternatively delete this folder which also holds cache information:

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\ifs_ifsweb
