### ISSUE TITLE
Unable to load World Map

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#22]
Date found: 2/1/2021
IFs Version: 7.62 dotNet
Found by: Barbara Stone
Error Type: Missing features

Description: Under Data Analysis, World Map selection does not load
Steps to replicate: Data Analysis> World Map

Reproducible in VB6 (Y/N): No, this functionality works in VB6

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce in version 7.65
