### ISSUE TITLE
Error loading Environmental list in Flex Display in .NET

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#220]
Environment, Global Average Temperature Not Country Based gives this error

<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Error Handler for IFsWeb.</h2><hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

The following error occurred:Exception of type 'System.Web.HttpUnhandledException' was thrown.System.NullReferenceException: Object reference not set to an instance of an object.at IFsWeb.frm_GraphicalDisplay.Page_Init(Object sender, EventArgs e) in C:\Users\solox\AppData\Local\Temp\WebSitePublish\IFsWeb--1602039507\obj\Debug\AspnetCompileMerge\Source\frm_GraphicalDisplay.aspx.vb:line 239at System.Web.UI.Control.OnInit(EventArgs e)at System.Web.UI.Page.OnInit(EventArgs e)at System.Web.UI.Control.InitRecursive(Control namingContainer)at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)The IFs project will appreciate and thank users that report any errors they might find, in either the web-based or stand-alone version of IFs including a reproducible path for generating the error (please provide details clearly) to jsolorza@du.edu. Thank you for using IFs and making it better.
--

</body>
</html>Error Handler for IFsWeb.
The following error occurred:

Exception of type 'System.Web.HttpUnhandledException' was thrown.
System.NullReferenceException: Object reference not set to an instance of an object.
at IFsWeb.frm_GraphicalDisplay.Page_Init(Object sender, EventArgs e) in C:\Users\solox\AppData\Local\Temp\WebSitePublish\IFsWeb--1602039507\obj\Debug\AspnetCompileMerge\Source\frm_GraphicalDisplay.aspx.vb:line 239
at System.Web.UI.Control.OnInit(EventArgs e)
at System.Web.UI.Page.OnInit(EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

The IFs project will appreciate and thank users that report any errors they might find, in either the web-based or stand-alone version of IFs including a reproducible path for generating the error (please provide details clearly) to [jsolorza@du.edu](mailto:jsolorza@du.edu?body=Exception%20of%20type). Thank you for using IFs and making it better.

**Comment by PardeeCenterIFs** [comment]
This one has been fixed, the problem was related to handling long URLs for the particular case of Lists that have no dimensions. The fix will be included in version 7.89.
