### ISSUE TITLE
Scenario screen - expand the label below the plot to show the name and definition of scenario parameter 

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#229]
The parameter selected in the screenshot pasted here has a second dimension that gets hidden both in tooltip and in the text label underneath the plot. Is there any way we can increase the height/width of the box so we can see the whole thing?

![image](https://user-images.githubusercontent.com/53452620/203194873-ed3eb042-5cbb-4167-a1bf-a2604394927b.png)

**Comment by mtirfan66** [comment]
Show Computed Function screen has a similar issue as shown in the screenshot below


![image](https://user-images.githubusercontent.com/53452620/204071423-42d8c91a-a209-411b-8f16-9e2356e20fcf.png)

**Comment by PardeeCenterIFs** [comment]
I have now increased the size of the box for the parameter description in the tree, but I realized that box doesn't exist in the web GUI, so I'll ask Jaime to please add it when he has a chance. Couldn't fix the width of the tooltip in vb6, it must have a hard max length.

I also increased the width box where we show Function Names in vb6, no problem with .NET.

**Comment by PardeeCenterIFs** [comment]
I have now added the variable description box in .NET, it will be included in version 8.03.
