### ISSUE TITLE
Blow-up in .net with Flex Display

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#231]
In 7.92 I choose Flex Display, Search Lists.  When I search I get a blow-up.

<html>
<body>
<h2>Error Handler for IFsWeb.</h2><hr><table width="100%" style="z-index: 101; left: 16px; position: absolute; top: 88px;"><tbody><tr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td><span id="lblError" style="height: 32px;">The following error occurred:<br><br>Exception of type 'System.Web.HttpUnhandledException' was thrown.<br>System.Data.OleDb.OleDbException (0x80004005): Could not find file 'C:\Users\jonathan.moyer\AppData\Local\IFs\RUNFILES\datadict.MDB'.<br>at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)<br>at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)<br>at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)<br>at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)<br>at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)<br>at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)<br>at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)<br>at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)<br>at System.Data.OleDb.OleDbConnection.Open()<br>at IFsWeb.frm_SearchVList.cmdSearch_Click(Object sender, EventArgs e) in C:\Users\solox\AppData\Local\Temp\WebSitePublish\IFsWeb--1602039507\obj\Debug\AspnetCompileMerge\Source\frm_SearchVList.aspx.vb:line 78<br>at System.Web.UI.WebControls.Button.OnClick(EventArgs e)<br>at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)<br>at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)<br>at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)<br>at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)<br>at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)<br><br>The IFs project will appreciate and thank users that report any errors they might find, in either the web-based or stand-alone version of IFs including a reproducible path for generating the error (please provide details clearly) to<span> </span><a href="mailto:jsolorza@du.edu?body=Exception%20of%20type" system.web.httpunhandledexception'="" was="" thrown.<brsystem.data.oledb.oledbexception="" (0x80004005):="" could="" not="" find="" file="" 'c:\users\jonathan.moyer\appdata\local\ifs\runfiles\datadict.mdb'.="" at="" system.data.oledb.oledbconnectioninternal..ctor(oledbconnectionstring="" constr,="" oledbconnection="" connection)="" system.data.oledb.oledbconnectionfactory.createconnection(dbconnectionoptions="" options,="" dbconnectionpoolkey="" poolkey,="" object="" poolgroupproviderinfo,="" dbconnectionpool="" pool,="" dbconnection="" owningobject)="" system.data.providerbase.dbconnectionfactory.createconnection(dbconnectionoptions="" owningconnection,="" dbconnectionoptions="" useroptions)="" system.data.providerbase.dbconnectionfactory.createnonpooledconnection(dbconnection="" dbconnectionpoolgroup="" poolgroup,="" system.data.providerbase.dbconnectionfactory.trygetconnection(dbconnection="" taskcompletionsource`1="" retry,="" useroptions,="" dbconnectioninternal="" oldconnection,="" system.data.providerbase.dbconnectioninternal.tryopenconnectioninternal(dbconnection="" outerconnection,="" dbconnectionfactory="" connectionfactory,="" system.data.providerbase.dbconnectionclosed.tryopenconnection(dbconnection="" system.data.providerbase.dbconnectioninternal.openconnection(dbconnection="" connectionfactory)="" system.data.oledb.oledbconnection.open()="" ifsweb.frm_searchvlist.cmdsearch_click(object="" sender,="" eventargs="" e)="" in="" c:\users\solox\appdata\local\temp\websitepublish\ifsweb--1602039507\obj\debug\aspnetcompilemerge\source\frm_searchvlist.aspx.vb:line="" 78="" system.web.ui.webcontrols.button.onclick(eventargs="" system.web.ui.webcontrols.button.raisepostbackevent(string="" eventargument)="" system.web.ui.webcontrols.button.system.web.ui.ipostbackeventhandler.raisepostbackevent(string="" system.web.ui.page.raisepostbackevent(ipostbackeventhandler="" sourcecontrol,="" string="" system.web.ui.page.raisepostbackevent(namevaluecollection="" postdata)="" system.web.ui.page.processrequestmain(boolean="" includestagesbeforeasyncpoint,="" boolean="" includestagesafterasyncpoint)'="">jsolorza@du.edu</a>. Thank you for using IFs and making it better.<br><br></span></td></tr><tr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
</body>
</html>Error Handler for IFsWeb.
The following error occurred:

Exception of type 'System.Web.HttpUnhandledException' was thrown.
System.Data.OleDb.OleDbException (0x80004005): Could not find file 'C:\Users\jonathan.moyer\AppData\Local\IFs\RUNFILES\datadict.MDB'.
at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
at System.Data.OleDb.OleDbConnection.Open()
at IFsWeb.frm_SearchVList.cmdSearch_Click(Object sender, EventArgs e) in C:\Users\solox\AppData\Local\Temp\WebSitePublish\IFsWeb--1602039507\obj\Debug\AspnetCompileMerge\Source\frm_SearchVList.aspx.vb:line 78
at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

The IFs project will appreciate and thank users that report any errors they might find, in either the web-based or stand-alone version of IFs including a reproducible path for generating the error (please provide details clearly) to [jsolorza@du.edu](mailto:jsolorza@du.edu?body=Exception%20of%20type). Thank you for using IFs and making it better.

**Comment by PardeeCenterIFs** [comment]
The original problem has been fixed, but I'm finding other places where we're still using OleDbDataAdapter, so the fix for the original fix will be included in version 7.93, and I'll keep checking other places. Next is gLoadMortProbChldL5 and gLoadMortProbAdlt.
