### ISSUE TITLE
History Always Displayed In Flex Display

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#233]
History Always Displayed In Flex Display

Date: 2023/01/12
Version: 7.92 .Net Development - Rebased to 1995; Also present in equivalent install
Branch: Threat
Found by: Caleb Petry
Error Type: Display Issue

While using flex display, regardless of the variable selection, history is displayed if available or nulls back to 1960 if unavailable.

![image](https://user-images.githubusercontent.com/7695597/212389278-738da92d-6221-4f33-846d-1ad0e3a71828.png)

![image](https://user-images.githubusercontent.com/7695597/212389341-afc85631-aa0c-4fff-a6fa-acc39c53601f.png)

**Comment by PardeeCenterIFs** [comment]
Is this happening even if it's the first thing you do when open the model (after reset of IIS)?
This doesn't happen when the base year is 2017, right?

**Comment by caleb-petry** [comment]
Correct.

I don't think so, but I have been exclusively using 7.92 rebased to 1995. 

I updated my GUI at the same time I updated the model code, if that is relevant.

**Comment by PardeeCenterIFs** [comment]
I just ran the process for Guided Rebuild to 1995 and couldn't reproduce this issue or #232, my tables start in 1995 now

**Comment by caleb-petry** [comment]
Hm... I cleared out my IFsWeb folder and replaced it from shares, but the issue still occurs. I'll try clearing the browser cache to see if that helps.

**Comment by caleb-petry** [comment]
Clearing the cache did not help with this issue.

**Comment by caleb-petry** [comment]
Behaves normally with 7.93 GUI, closing for now.
