### ISSUE TITLE
GDP Growth Errors When Chinese Growth Changes

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#235]
GDP Growth Errors When Chinese Growth Changes

Date: 2023/02/07
Version: 7.93 .Net Development - Rebased to 1995
Branch: Threat
Found by: Caleb Petry
Error Type: Bug

![image](https://user-images.githubusercontent.com/7695597/217388023-d66e29a3-d3bc-46bf-a653-da4b2d1f5119.png)

The blue line above is the one indicating the issue.

To replicate, rebase to 1995 ~and use _igdpr_ to increase Chinese growth rates (0.035 increase in the example above)~ (this was actually a hardcoded version as described in Barry's email, but I had the error occur with _igdpr_ also). This bug does not occur in a 1995 base year 7.92 .Net Development version. I tried to replicate this bug in a 7.93 VB6 install, but could not.

I tried reducing _igdpr_ and got similarly unexpected results.

The issue does not appear to be limited to _igdpr_ parameter usage as the initial identification included hard-coded sectoral growth rate increases for China.

The pathway to growth spikes in 1997 seems to begin with trade values spikes in 1996 causing MFPKN to behave poorly.

The hard coded version is: 

> I replaced: "sectorgr(R%, S%) = AMAX(sectorgr(R%, S%), POPR(R%) / 100 + minpcgr(R%)) 'jrs 2021/08/16"
>
> With (something along the lines of):
>
> "sectorgr(R%, S%) = AMAX(sectorgr(R%, S%), POPR(R%) / 100 + minpcgr(R%)) 'jrs 2021/08/16
 > If S% > 2 And GRPS(1, R%) = "China" Then sectorgr(R%, S%) = AMAX(sectorgr(R%, S%) + 0.035, POPR(R%) / 100 + minpcgr(R%)) 'jrs 2021/08/16"

**Comment by caleb-petry** [comment]
Barry attempted to reproduce in 7.93 VB6 Dev and could not.

I attempted to reproduce it in a 7.93 .Net install and could not.

I will try reproducing the issue in a clean 7.93 .Net Dev.

**Comment by caleb-petry** [comment]
@solox1, are we good to close this issue with the updates in 7.94?

**Comment by PardeeCenterIFs** [comment]
Yes, this should be fixed in 7.94
