### ISSUE TITLE
Sector Dimension Option Missing In Flex Display For Some Displays

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#242]
Title: Sector Dimension Option Missing In Flex Display For Some Displays

Version: 7.97 Model w\ Different TFR and Agricultural Trade Quantity/Value Data; 7.96 GUI

Description: When attempting to use some variables, the dimension is not included in the selectable options in Flex Display. The first category (for example, Agriculture for economic sectors) is shown instead when a table or line graph is displayed.

Replication:
1. Open Flex Display
2. Select "Economy Productivity"
3. Select "Labor productivity by sector"
4. Open a table or line graph

I've noticed this with another variable as well, but can't recall where at this time.

**Comment by PardeeCenterIFs** [comment]
I think this one is fixed, yesterday while loading a new series from Barry I realized that table VarListsHdr was not being automatically updated, so there could be issues loading dimensions, but I have now fixed that, and this issue should be solved in version 8.02.
