### ISSUE TITLE
Model Crash After Continuing Away From Flex Display

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#243]
Short Description: Model crash after continuing away from Flex Display
Date found: 08/08/2023
IFs Version: IFs 8.03 Model and GUI
Description: I've ran into this one intermittently but had some consistency in replicating it this time.  From Flex Display: 
1. Select GDP (no history), 
2. Select 2040,
3. Select all countries
4. Do B-A Comparison
5. Open line graph then close
6. Attempt to continue back to Flex Display variable select
7. Crash

Reproduced, but inconsistent; Not opening the line graph or removing the B-A comparison seems to avoid the crash.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/7695597/bdb54686-dcf8-4ba8-99bf-e51f0544d561)

**Comment by PardeeCenterIFs** [comment]
Thank you for finding this one Caleb, I was able to address the issue, and the fix will be included in version 8.04.
