### ISSUE TITLE
Bilateral Display Crash When Using Comparison Options

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#247]
Bilateral Display Crash When Using Comparison Options
IFs 8.04+ Development

To reproduce:
1. Open bilateral display
2. Select forecast variables and scenario for display
3. Open 
4. Select comparison option 
5. Exit table to main display
6. Reopen, check comparison options
7. Disable comparison option
8. Crash

> The following error occurred:
> 
> Exception of type 'System.Web.HttpUnhandledException' was thrown.
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
> at System.Array.InternalGetReference(Void* elemRef, Int32 rank, Int32* pIndices)
> at System.Array.GetValue(Int32 index1, Int32 index2)
> at Microsoft.VisualBasic.CompilerServices.Symbols.Container.GetArrayValue(Object[] Indices)
> at Microsoft.VisualBasic.CompilerServices.NewLateBinding.InternalLateIndexGet(Object Instance, Object[] Arguments, String[] ArgumentNames, Boolean ReportErrors, ResolutionFailure& Failure, Boolean[] CopyBack)
> at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateInvokeDefault(Object Instance, Object[] Arguments, String[] ArgumentNames, Boolean ReportErrors, Boolean[] CopyBack)
> at Microsoft.VisualBasic.CompilerServices.NewLateBinding.InternalLateInvokeDefault(Object Instance, Object[] Arguments, String[] ArgumentNames, Boolean ReportErrors, Boolean[] CopyBack)
> at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateIndexGet(Object Instance, Object[] Arguments, String[] ArgumentNames)
> at IFsWeb.frm_BilateralInteractionDisplay.LoadGrid() in C:\Users\Public\IFs\IFsWeb\frm_BilateralInteractionDisplay.aspx.vb:line 752
> at IFsWeb.frm_BilateralInteractionDisplay.mnuCompReset_Click() in C:\Users\Public\IFs\IFsWeb\frm_BilateralInteractionDisplay.aspx.vb:line 1041
> at IFsWeb.frm_BilateralInteractionDisplay.ItemClickHandler(Object sender, EventArgs e) in C:\Users\Public\IFs\IFsWeb\frm_BilateralInteractionDisplay.aspx.vb:line 977
> at Coalesys.WebMenu.WebMenu.OnServerItemClick(ServerItemClickEventArgs eventArgs)
> at Coalesys.WebMenu.WebMenu.RaisePostBackEvent(String eventArgument)
> at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
> at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
> at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by PardeeCenterIFs** [comment]
I was able to reprode and fix this issue. The fix will be included in version 8.06.
