### ISSUE TITLE
Three Country Selection Boxes After Bilat Display

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#248]
Versions: 8.04+ Development; 8.05 Install

To replicate (Perhaps unnecessary steps, but I had trouble replicating it):
1. Open bilateral display
2. Select Africa-Africa and Africa-World
3. Select XDYAD
4. Select two scenarios
5. Open table
6. Close table
7. Select MDYAD also
8. Open table
9. Select a/b from comparison objects
10. Close table
11. Continue back from bilateral display
12. Open Flex Display
13. See...

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/7695597/385019bf-9704-4175-8bab-7838106946c3)

Continuing back and reloading Flex Display seems to fix this issue.

**Comment by PardeeCenterIFs** [comment]
I was able to reproduce and fix this issue. The fix will be included in version 8.06.
