### ISSUE TITLE
Options on graphics (particularly of doubly dimensioned variables) for changing legends to dimensions do not work

### ISSUE THREAD

**Issue by BarryBHughes** [PardeeCenterDU/IFs-Issues-Tracking#250]
In flex display if one selects geographic lists (and I am testing with the Chile, OECD, World list) and selects a singly dimensioned variable like GDP, a graphic will bring up the display with legends that show Chile, OECD, and World, but without the variable name shown.  The absence of the variable name is not a problem (in fact quite an asset) but a bit disconcerting given that we get those names with doubly-dimensioned variables as indicated in the next paragraph.

If one selects a doubly-dimensioned variable such as Agricultural Demand (same geography list and crop as second dimension), a graphic with the variable name and both dimensions shown.  Most of the sub-options under Display Format do not seem to be working at all.  For instance, click on First Dimension Only, Second Dimension Only, No Dimensions, or Scenario Names – nothing in the graphic changes.  Format legend labels does work, giving one basic control over the legend names, so there is a work-around – but for a graphic with half a dozen or more countries like the one below, that is quite a pain.

**Comment by PardeeCenterIFs** [comment]
This issue has been fixed, and it will be included in version 8.09
