### ISSUE TITLE
Rounding issue in data vetting process

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#253]
When IFs is loading table and adding values for the MostRecent column, it adds arbitrary floating numbers to the end. See the screenshot attached below.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/305c5576-87e9-48e3-abbd-e7f1945fbe63)

I've also attached the IFsDataImport file here. 
[PIP Pov TG 20231031.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/13219206/PIP.Pov.TG.20231031.zip)

**Comment by PardeeCenterIFs** [comment]
Could you please be more specific on how to reproduce this issue. What form, and what button or menu option should I click?
What variable are you using for the example, the attached includes several.

**Comment by quciet** [comment]
> Could you please be more specific on how to reproduce this issue. What form, and what button or menu option should I click? What variable are you using for the example, the attached includes several.

Open the IFsDataImport.db in the attached file through IFs vet data import function, you can see these values in the MostRecent column

**Comment by PardeeCenterIFs** [comment]
Those extra decimals are what's on the ifsHistSeries.db file, I'm only reading the file from RUNFILES, check GiniExtended for example.

**Comment by PardeeCenterIFs** [comment]
I just tested importing only GiniExtended, and the extra decimals go away, since the problem is not there in the IFsDataImport.db.
