### ISSUE TITLE
Wrong data format after importing

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#254]
Hi there,

When multiple data tables are being imported into IFs, the format of resultant table sometimes gets messed up. The recording below shows the process. Towards the end, you can see that the output is in a weird form.

https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/2a05592b-cfde-4fee-b7fd-30f200b1d0ba

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/b9ba6e63-ad5d-4f0b-a216-62565039ea5a)

I've also attached the Excel file used for importing.
[ITU_Data_Clean.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/13219258/ITU_Data_Clean.xlsx)

**Comment by PardeeCenterIFs** [comment]
I was able to fix this issue, the fix will be included in version 8.11.
Thank you for the clear example and video.
