### ISSUE TITLE
Showing start year in the rebuild base and run forms

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#26]
The rebuild base and the run forms (image attached) do not show the start year. Displaying the start year is very useful, especially for people working on multiple rebase years.

Date requested: 03/18/2021

IFs Version: VB6 all

Requested by: Mohammod

Screenshot: Run form
![Runform](https://user-images.githubusercontent.com/53452620/111652995-c39b3280-87c4-11eb-8050-da78657258fb.JPG)

Discussion:

**Comment by PardeeCenterIFs** [comment]
I have added a Base Year label to both the rebuild base and run forms, they will be included in version 7.67
