### ISSUE TITLE
Features in Vetting not working

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#260]
Some features seem not to work correctly under the Vet & Merge interface. 

Using this IFsDataImport as an example ([IFsDataImport_KS.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14286612/IFsDataImport_KS.zip)). I'm looking at the table ViolenceInterpersonChild, it seems the Mark the difference between new and old data tab is not working correctly, it refreshes the interface but nothing happens. It is not marking any differences between old and new data. For example, values in Afghanistan in 1990 have a big gap. 
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/91a69668-3389-4dea-a497-f7c6607a4208)

Other two functions work just fine, i.e., make year to year jump in either old or new data, or make points above or below a certian threshold. However, there is not a clear or refresh button for me to clear all the marked points. The only way I found so far is go to the list of tables and click "Select" to reload tables again.

Also, when I click on plot selected countries, I received an error message.
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/21b83544-87d6-49e8-81e4-0a2fa0bbe516)

**Comment by PardeeCenterIFs** [comment]
I have now fixed the Marking not working, the plot giving an error, and also updated the other markings so that they don't work on top of each other, but reset to blank the rest of the cells, so if you want to reset you could say mark all above value, and set the value very high. Fixes will be included in version 8.18.
