### ISSUE TITLE
IFs version number in plot screen

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#262]
Is there anyway we can put the IFs version number underneath the Pardee image in the plot area, may be with a toggle on the top menu to take it on/off. If that is too complicated, can we actually keep the version number in the browser window caption, like we do with main menu?

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/9c6fb9ba-72c6-423e-8929-ffd7833b674d)

**Comment by PardeeCenterIFs** [comment]
This has been implemented and it will be included in version 8.32, the version is visible for default, but we can make it invisible by default easily if that's preferred.
