### ISSUE TITLE
Recording of Scenario File bugs

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#267]
Here's the recording:  https://udenver.zoom.us/rec/share/En46OAcvCAAO339SR3xNXBVqvhHsR_CRGeSupfe6OrS6QYptvpSHX_j8UTuvbHIF.QOyAn-LRvZplRPeI 
Passcode: dCr1y3#M

It's quite long, but there are two bugs it shows clearly.  One occurs when I'm creating sce interventions in quick scenario and the model adds a random number in the first year after I've hit exit to scenario.  The other occurs when I'm trying to change ylm (or I think it's ylm--it's at the bottom of the tree and causes an error)

**Comment by PardeeCenterIFs** [comment]
I just tried following this link, and get a message, the recording doesn't exist.
