### ISSUE TITLE
We need to extend the definition of confforsw

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#268]
It has three settings, and I am currently using setting 2, but I can't remember what it does and it's not in the definition for the parameter.  Should be something Jose can add easily (he added the parameter--again, I'm just forgetting what it does)

**Comment by PardeeCenterIFs** [comment]
I have changed the descritption as follows:

Conflict forward linkage switch (2 = On but only MFP effect, 1=On Full effect, 0=Off)

This change will be included in version 8.19
