### ISSUE TITLE
Weird Scenario Analysis bug?

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#269]
I reproduced it twice... attached is an sce file
[SSP3 - Copy.sce.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14454493/SSP3.-.Copy.sce.txt)

If you open this in quick scenario analysis, go to the parameter intervention for sfintlwaradd in the tree, click customize, I got this to blow up twice by changing the value to 0 for 6 years, then selecting 1.1 for 100 years interpolation.

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce, I just get a warning that we're trying to go beyond the 1.0 maximum.
