### ISSUE TITLE
ifsdataimport logic change

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#271]
Currently, whenever users click OK on the starting page of Import Data (Single Series) after all other fields are set, IFs will add a table to IFsDataImport.db, without waiting for users to click Accept Data in the 2nd working page where IFs formatted data table is shown. Even users hit the Cancel button, the table won't be removed from the file.

After users click Accept data and click ok once filling in information in the DataDict in the 3rd working page, IFs will then add entries to the DataDict table under the IFsDataImport.db file. 

I suggest that, 
Option 1. After users click Cancel, that table should be removed from the file.
Or option 2. Table and its meta-data should be added all at once at the end after users hitting OK in the 3rd working page.

**Comment by PardeeCenterIFs** [comment]
I have now implemented option 1, I'm now removing that table when the user clicks Cancel. This will be included in version 8.19.
