### ISSUE TITLE
scenario tree blowup

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#272]
In either of these sce files, load them in the tree, go to sfintlwaradd, and try to make a customed change.  you get an error when you try to go back to the tree.
[SSP4.sce.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14466861/SSP4.sce.txt)
[SSP3.sce.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14466862/SSP3.sce.txt)

**Comment by PardeeCenterIFs** [comment]
Got it, I have fixed this one, and it will be included in version 8.19.
