### ISSUE TITLE
Government spending on education data: Cuba

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#273]
Cuban educational spending, as a % of GDP, is **initialized at a much lower value** (first screenshot) than what the WDI data shows (second screenshot).
The data table had a bunch of empty cells in the Access database (third screenshot). They show as 0s in the SqLite database (fourth screenshot). 
The date of update for the data table (**SeriesGovtEdPub%GDP**) in the datadict.db is 2023/07/25. In addition to fixing the Cuban data, I request an immediate careful examination of that entire table. This is an important data table. I was able to detect this only because I am familiar with Cuba’s educational spending pattens.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/fb50dd37-d304-4b29-9e70-63b1376a17cd)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/fd1dab17-de10-45b5-88fc-7de0101006d8)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/bb4a2ef6-99e6-4ae4-93e0-0831866f6b9a)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/11035f2c-1cf9-4a2b-9ad1-443b8c696e05)

**Comment by quciet** [comment]
A data task has been created for this, https://www.wrike.com/open.htm?id=1320709558. The table has been pulled and vetted. It will be included in the next delivery (likely IFs8.20 or 8.21)
