### ISSUE TITLE
Different number of decimal points in imported data

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#276]
I'm using this file as an example [pip_215.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14577685/pip_215.xlsx). When importing, the MostRecent column produces more number of decimal points than required. 

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/ee21fa06-7bf0-47f2-a815-259e1361a3dd)

In addition, I checked previous tables I merged to the master database and found an issue I was not able to explain. Poverty tables from WDI (IncBelow2D15c%, IncBelow3D65c%, and IncBelow6D85c) were brought in during the WDI batch pull (database version **IFsHistSeries 8.05 + WDI 20230911**). Here is the IFsDataImport.db file that was merged into the master database [IFsDataImport WDI.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14577943/IFsDataImport.WDI.zip). In that update, values in these tables are normal. See the screenshot below,
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/c7d190fd-0361-477d-9c4a-6b91fcc989a2)

These tables have not been updated since then, you can double check that by looking at the DataDict table, the last update date is still 2023/07/25. However, values in those tables are showing a weird pattern now, i.e., inconsistent number of decimal points between the actual data values and the most recent column. I checked several versions of database in IFs and think this happened as early as IFs version 8.09. 
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/e03fd8cf-7b18-45d0-aa36-0c4fa401351b)

Any idea why this is the case? Thanks!

**Comment by PardeeCenterIFs** [comment]
I found the MostRecent rounding issue, and it was easy to fix, that will be included in version 8.19.

Regarding the issue you're showing bellow, is it possible it's the same issue you were talking to Mohammod where some Nulls were replaced with 0s? notice that the 0.4 MostRecent value is the most recent non-zero value. Or maybe is the MostRecent logic, that is not detecting 0s.

**Comment by PardeeCenterIFs** [comment]
Could you try importing this again, just the one table and checking if the 0s are not taken into account for the most recent field in the most recent version of the GUI.

**Comment by quciet** [comment]
Thanks! I tested it with version 8.19 and the issue is now gone.
