### ISSUE TITLE
Demographic Display Issue:  Cant Select Scenarios

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#277]
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/85649722/951a37c5-da78-4668-9e9e-311df2f2e343)

In Population Graph choose Change Display, Change Scenario, and many scenarios are not displayed

**Comment by PardeeCenterIFs** [comment]
Can't reproduce it:

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/2348d6a5-6995-4065-8cc0-cd9d3d5f1f9e)
