### ISSUE TITLE
Customizing horizon for plot displays, especially history and forecast

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#28]
Customizing the start year of plot displays now requires using the Graph control's menu dialog as shown in the image. It would be great to have an IFs menu option that allows saving a custom _start_ year for plot displays. This is especially useful for history and Forecast displays as evident in the screenshot. We can also think about a second additional feature along the line of this - a menu option in the flex display to save the display horizon with a start and end year (only the end of the horizon can be chosen now). If this feature is added, it could be a toggle option (to back and forth between the custom horizon and default horizon).

![plot HnF](https://user-images.githubusercontent.com/53452620/111921534-57356300-8a52-11eb-8ff4-c4fba3cebd1d.jpg)

**Comment by mtirfan66** [comment]
![image](https://user-images.githubusercontent.com/53452620/123769285-fc47af00-d87d-11eb-8f49-b3ac814976e4.png)

**Comment by mtirfan66** [comment]
Could someone please tell me why this issue is closed? Is it something that will be done in .net and not in VB6? Is there any bottleneck anyone is facing in implementing this? Thank you.

**Comment by mtirfan66** [comment]
If it is already done please let me know. Thank you once again.

**Comment by Coryv221** [comment]
As an update, this feature is implemented as a unstable feature that is going to be tested by the Documentation team. Once any lingering bugs are fixed, we will deploy it in the next upcoming consolidation, and close the issue!

**Comment by Coryv221** [comment]
All remaining bugs are resolved, and this feature will be in the next consolidation of IFs
