### ISSUE TITLE
Long-term issue in traffic accidents

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#282]
![chart - 2024-03-15T131634 889](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/85649722/b05f8ec9-7395-4d23-8b22-5689f4671571)

**Comment by PardeeCenterIFs** [comment]
The fix for this issue will be included in version 8.20, this is one that wasn't ready for more than 100 years.
