### ISSUE TITLE
health display

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#284]
it's not possible, in my understanding of how to use the tool, to get a display that a) uses deaths, b) uses a non-base case scenario, c) has the oldest cohort selected, and d) changes the year.

**Comment by PardeeCenterIFs** [comment]
The only one that wasn't working was the one where you changed scenario, but since that one is fixed in version 8.20 this all should work now.

**Comment by PardeeCenterIFs** [comment]
There have been more fixes in version 8.22, so this should work ok now.
