### ISSUE TITLE
Flex Display Dimension Box with Female and Male

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#289]
When I choose 'Male' from the dimension box (as shown in screenshot 1), navigate to the Table Display (screenshot 2), and return to the Flex Display, I notice that 'Female' is now automatically selected (as shown in screenshot 3). This behavior also occurs when I select 'Female'; upon returning to the Flex Display, 'Male' becomes the selected option.
I'm not sure if this is intentional design. Personally, I would prefer if the selection remained unchanged and did not switch automatically.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/e17843d2-edf7-4944-883f-31bd893181ac)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/690faa66-63ba-4425-b2d9-de32c1b0d4f1)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/3ded0cd9-030c-43ab-8187-1d96c00a6f05)

**Comment by PardeeCenterIFs** [comment]
This issue was introduced with the option to have Females first, developed by Cory. The fix will be included in version 8.21.
