### ISSUE TITLE
Flex Blow-up

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#291]
In Flex (8.20 and online version) this configuration doesn't work.  If the image isn't showing up it's death rates by category of cause for the world, total and total

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/85649722/8c4f88c7-ad7f-4766-b238-ad1f719e2b84)

**Comment by PardeeCenterIFs** [comment]
It works fine in version 8.21
