### ISSUE TITLE
Health Display issues

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#293]
if you, for example, choose a group (world) and a distribution type (say communicable disease) and you choose a scenario (say, No COVID), then pick a year (say, 2024).  Now the scenario goes back to the base.  You can't pick a custom year and scenario at the same time.

**Comment by PardeeCenterIFs** [comment]
Got it, I think I finally got it this time, it should be fixed in version 8.22

**Comment by jonathandmoyer** [comment]
Great!
