### ISSUE TITLE
Table Display -  Display Options- Start Year Divisible by 5

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#299]
Table Display -  Display Options- Use Start year divisible by  works great when it is selected for the first time. However, if you then change the display interval (this step might not be necessary, I am not sure, but this is how I got it), that also works. Now if you go back to flex display and come back for another table display. The Use Start Year Divisible by 5 is still selected. However, the start year now is 2019, as shown in the screenshot below. 
To make it working again, I had to unselect Use Start Year Divisible by 5 (or, set it to off), change the display interval back to 1, and then reselect the start year divisible by 5 and do the change display interval again.      

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/b1191640-1c96-4647-8da5-93535722d4ee)

**Comment by PardeeCenterIFs** [comment]
I have fixed this, and the fix will be included in version 8.32.
