### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#3]
Date found: 10/13/20
IFs Version: 7.56 .NET Install
Found by: Luca Picci
Error Type: Blowup
Description: IFs generated a timeout error on two occasions even though I was actively using IFs and had not had the application open for more than 30 minutes
Steps to Replicate: N/A – normal use of IFs
Reproducible in VB6 (Y/N): N/A
[IFs.NET.Timeout.Error.docx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/6093531/IFs.NET.Timeout.Error.docx)

**Comment by PardeeCenterIFs** [comment]
This that improved this situation, we hired a consultant to analyze our code and improve our situation, and he recommended and later implemented the following:

1.	Upgrade to Web Application using most recent version of .NET Framework (4.8.1), including the implementation of Logs.
2.	Implementation of Light Weight reading logic to access our output files, reducing memory needed to load our results.
3.	Update Model Code to use .NET 8, benefitting from the most recent version of the language.
4.	Improving the interaction between the Interface and the model in the Run screen, removing session variables and using Javascript to improve user experience.

The first 3 were included in version 8.20, the last one in version 8.22.

Also as part of option 1 we included a new logging sistyem which helps us better tackle errors.
