### ISSUE TITLE
VB6 7.61 2017 base - Population display

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#30]
Population by age and Sex and Birth Cohort Information – start year is 2017 base year but “advance” option interval is 5 years from base year so next years are 2022, 2027

Display, specialized display for issues, population by age and sex

VB6 7.61 2017 rebase

![image](https://user-images.githubusercontent.com/56567716/113626344-46264d80-961f-11eb-825f-1eac6d64485c.png)

**Comment by Coryv221** [comment]
Also exists for VB.net
