### ISSUE TITLE
Table Display -  Display Options- Change Display Interval - can we add choices in the submenu?

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#300]
For Table Display -  Display Options- Change Display Interval we have to go to a second screen each time we need to change it. Is there anyway we can have a small submenu attached with, 1, 5, 10 and custom and the "custom" is the only one that makes user go to that second screen?

**Comment by PardeeCenterIFs** [comment]
I have now added these custom 1, 5, 10 and custom options to Table Display, these will be included in version 8.32.
