### ISSUE TITLE
Cannot see grade enrollment rates anymore

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#303]
Jose,
I'm on 8.21. I cannot see grade enrollment rates anymore, even though the switch (edmodelsw) is set to 1 and I rebuild base and ran scenarios after setting the switch. The switch values show as 1 in self managed display.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/f2e61833-c810-4c64-8401-07aa9f7571bc)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/952869e3-f56d-4af9-9937-12d5115c256d)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/6b2dd30b-871e-4c6f-81eb-aa52e560c7ee)

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce this one on my version

**Comment by PardeeCenterIFs** [comment]
The IFs.Data.Lite, and IFs.IData.Lite needed to be updated, last update was on April 17th
