### ISSUE TITLE
Performance Risk not working

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#306]
In 8.23 it says this:
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/85649722/f6f6957e-f9c8-4f42-9ebf-1807f86aa9d6)

**Comment by PardeeCenterIFs** [comment]
Sorry about that, this was left over from when it was disabled in non-development version. I have now removed that check, it will be included in version 8.24.
