### ISSUE TITLE
Computation not working on Data (cross sectional) plot

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#309]
I could not type a divided by 1000 for GDPPC2017PCPPP, to select it as an independent variable. When I used Computation, I got a bad plot.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/cfc77224-92d2-45e9-8a6a-5b4a5b9de272)

Video here:
https://drive.google.com/drive/folders/1xaWNquyy1CKPeXxDCpn7tqJFOlZuFii7?usp=sharing

**Comment by PardeeCenterIFs** [comment]
I see you're using version 8.21 in this example, this problem was solved in version 8.24.
