### ISSUE TITLE
VB6 7.61 2017 base - Cohort Display

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#31]
Horizontal axis labels are off. See screenshot below

Display, specialized display for issues, cohort display

![image](https://user-images.githubusercontent.com/56567716/113627383-ab2e7300-9620-11eb-831d-b99ccbeed7d3.png)

**Comment by Coryv221** [comment]
@lpicci96 What steps did you take to create this problem?

**Comment by lpicci96** [comment]
If select Year: 2021, that output will be displayed. Same issue is in 7.66.

![image](https://user-images.githubusercontent.com/56567716/118701272-c1f3e800-b7d0-11eb-8836-b5fb09e6fc1b.png)
