### ISSUE TITLE
allow users to select and read their own IFsDataImport.db

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#312]
Currently, in the Vet and Merge Imported Data function (under Extended Features), users will have to put IFsDataImport.db file under the RUNFILES folder to read the IFsDataImport.db file. 

Can we add a function in that interface to allow users to browse and select their own .db file? This was a function in VB6 version of IFs but was lost during the translation. Thanks!

**Comment by PardeeCenterIFs** [comment]
I have now implemented this option, and it will be included in version 8.26.
