### ISSUE TITLE
IFs running the model 

### ISSUE THREAD

**Issue by n1shamin** [PardeeCenterDU/IFs-Issues-Tracking#314]
Hello, 

I went to rebuild a base and rerun a model because originally I only rebuilt the base to 2050 and I need 2100. The rebuild was successful but there was an error in running the model. I got these errors:
![Screenshot 2024-05-31 180049](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/168131965/190f6dfa-a9cb-44e5-abb8-e7c56293af22)

**Comment by quciet** [comment]
adding related log file here- 

[2024-05-31.log](https://github.com/user-attachments/files/15571382/2024-05-31.log)

**Comment by quciet** [comment]
From José's comment, 

resetting the IFsBase.run file seems to fix the issue.
