### ISSUE TITLE
add one more preprocessor table for military spending

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#315]
Currently, GovtMil%GDPWDI is being used as the preprocessor for reading military spending as a percentage of GDP. But it is missing some countries/areas. Please add in a secondary source for data inilization, table **SeriesGovtMil%GDPSIPRI**.

Thanks!

**Comment by PardeeCenterIFs** [comment]
Currently GovtMil%GDPWDI is the primary data source, but we already have a second data source on: SeriesGovtMil%GDP.

Do you want SIPRI to be the 3rd data source?

**Comment by quciet** [comment]
I think we should take GovtMil%GDPWDI as the first, SIPRI as 2nd. WMEAT is discontinued, we can leave it as 3rd and eventually remove it in the future. Thanks! 

> Currently GovtMil%GDPWDI is the primary data source, but we already have a second data source on: SeriesGovtMil%GDP.
> 
> Do you want SIPRI to be the 3rd data source?

**Comment by PardeeCenterIFs** [comment]
SeriesGovtMil%GDP has more recent data (2017 vs 2003) for Eritrea, so I think it's good we're keeping it

**Comment by quciet** [comment]
> SeriesGovtMil%GDP has more recent data (2017 vs 2003) for Eritrea, so I think it's good we're keeping it

Sounds good! So 3 tables in total for this. In the future if SIPRI starts to provide more recent values for Eritrea then we can consider removing it. Thanks!

**Comment by PardeeCenterIFs** [comment]
Ok, I just finished implementing this and it will be included in version 8.26.
