### ISSUE TITLE
threat received error

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#317]
Flex display, Internatioanl politics, afghanistan, threat received, line graph

<html>
<body>
<hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
The following error occurred:Exception of type 'System.Web.HttpUnhandledException' was thrown.System.ArgumentException: Invalid postback or callback argument. Event validation is enabled using in configuration or <%@ Page EnableEventValidation="true" %> in a page. For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them. If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.at System.Web.UI.ClientScriptManager.ValidateEvent(String uniqueId, String argument)at System.Web.UI.WebControls.ListBox.LoadPostData(String postDataKey, NameValueCollection postCollection)at System.Web.UI.WebControls.ListBox.System.Web.UI.IPostBackDataHandler.LoadPostData(String postDataKey, NameValueCollection postCollection)at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad)at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
--

</body>
</html>

**Comment by PardeeCenterIFs** [comment]
The problem was when switching from Core to Non-Filter, this was filling up the categories and variables only in the client not in the server, producing a security error, The fix is to force a trip to the server when you click on the Filter combo box.
This fix will be included in version 8.27.

As a work around you can setup the Non-Filter as the default in ifsInit, and that should allow you to use all lists.
