### ISSUE TITLE
IFsDataImport.db not being merged

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#320]
I've never seen this before. I'm using IFs8.25, and you can find IFsDataImport.db in the zipped file. 

I recorded a video showing the process. When I clicked "Merge", nothing happened and the interface just refreshed on itself. I've also attached the log file from IFs. 

[Debug.zip](https://github.com/user-attachments/files/15977902/Debug.zip)

**Comment by PardeeCenterIFs** [comment]
I think this file is corrupted, I tried Loading it with the code, and it just kept ignoring it. I can open it without any problems in SQLite Studio, but not from VS.

I then copy it manually into RUNFILES and tried merging, and it worked with no problems.

I would say there's something weird with the file, but overall coudn't reproduce the exact same issue.
