### ISSUE TITLE
VB6 7.61 2017 base - Health display

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#33]
Mortality by Age, Sex and Cause - start year is 2017 base year but “advance” option interval is 5 years from base year so next years are 2022, 2027. Same as #30 
**ALSO**:  the toolbar is different from others – no option for “advance” on the toolbar – need to select “change years” then “advance”

Display, specialized display for issues, mortality by age sex and cause.

![image](https://user-images.githubusercontent.com/56567716/113627916-66570c00-9621-11eb-9708-6a896a7fea37.png)

**Comment by Coryv221** [comment]
also in VB.NET
