### ISSUE TITLE
(Dyadic-driven) Monadic Migration Update To (Hopefully) Address Excess Population Declines

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#336]
This issue will be addressed following the monadic updates from WPP2024.

We have three main assumption options:
1. Constant Flow (preferred constant when populations increase globally)
2. Constant Rate (may work better for the Albanias of the world)
3. Model-based projections (finding a way to better incorporate WPP's newer probabilistic projections; this could be easy, but I have yet to think too much about it; Preferred if possible.)

See also: #283 #265 #239

**Comment by quciet** [comment]
Data have been updated, however, my understanding is that there are two obvious issues- 
1. There is an incompatibility between WPP2024 and Guy Abel data. 
2. 2020 might not be a good base year for migration due to Covid (check the latest monadic data for India and US)

**Comment by PardeeCenterIFs** [comment]
The data was update, and after tinkering a little with the algoright for balancing dyadic with monadic, we implemented a convergence to 0 of rates from 2100 to 2200. This is how MIGRATE(ALL) now looks:

![image](https://github.com/user-attachments/assets/78944868-42e5-40df-9503-a103714fb7ad)
