### ISSUE TITLE
VB6 7.61 2017 base - Mortality and Disability display

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#34]
Horizontal axis labels are off similar to #31 

Display, specialized display for issues, Mortality and disability years

![image](https://user-images.githubusercontent.com/56567716/113628320-f7c67e00-9621-11eb-96b0-4fb09c4246d1.png)

**Comment by Coryv221** [comment]
Also an issue in .Net

**Comment by Coryv221** [comment]
Tasks to do
Change interval to annual
Change to Line graph by Default
Option to switch between lines and bars
