### ISSUE TITLE
VB6 7.61 2017 base - Growth Accounting display

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#35]
Horizontal axis labels begin 2022 and advance 5 years. See screenshot below. Also you cannot set a specific year under any of the option in “display format”. You can only change the year interval. 

Display, specialized display for issues, growth accounting

![image](https://user-images.githubusercontent.com/56567716/113628974-efbb0e00-9622-11eb-8c5a-0b5a537220fc.png)

**Comment by Coryv221** [comment]
Growth Accounting Currently doesn't work on .Net, will be a bigger issue to fix

**Comment by Coryv221** [comment]
Tasks to do
Change interval to annual
Change to Line graph by Default
Option to switch between lines and bars
Set 3D to off
Shadow set to line
