### ISSUE TITLE
R&DGovt%GDP will not open in IFs Vetting page 

### ISSUE THREAD

**Issue by n1shamin** [PardeeCenterDU/IFs-Issues-Tracking#350]
When trying to open R&DGovt%GDP in the IFs vet and merge data feature, I keep getting the attached issue. Nothing appears wrong with the DataDict. 
![image](https://github.com/user-attachments/assets/aec24a31-e71b-494b-81ab-b3d713e6ff2e)

**Comment by PardeeCenterIFs** [comment]
Can you share your RUNFILES\IFsDataImport.db, the problem must be there, we need to check the mentioned table exists there, spelled exactly as the message says.

**Comment by n1shamin** [comment]
Here is the file. 
[IFsDataImport - Copy.zip](https://github.com/user-attachments/files/17740264/IFsDataImport.-.Copy.zip)

**Comment by PardeeCenterIFs** [comment]
Thank you, I was able to reproduce the issue, and I have made a change in the code to handle variables with "&" in the name. This fix will be included in version 8.35.
