### ISSUE TITLE
VB6 7.61 2017 base - World value display

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#36]
Start year is 2017 base year but “advance” option interval is 5 years from base year so next years are 2022, 2027. same as #30 

Display, specialized display for issues, World value survey by age

![image](https://user-images.githubusercontent.com/56567716/113629277-6f48dd00-9623-11eb-8a05-6921e043b36c.png)

**Comment by Coryv221** [comment]
Also an issue in .net
