### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#37]
Runtime error

Path: Display, Specialized Display for Issues, Development Priorities

VB6 7.61 (both 2015 and 2017 base)

![image](https://user-images.githubusercontent.com/56567716/113629631-f0a06f80-9623-11eb-8591-874654599450.png)

**Comment by PardeeCenterIFs** [comment]
I have fixed this one, and it will be included in version 7.66
