### ISSUE TITLE
Unstable links for IFs web line graphs if both country and group are selected

### ISSUE THREAD

**Issue by collinmeisel** [PardeeCenterDU/IFs-Issues-Tracking#39]
Hi there,

Since at least April 2019, I've noticed an issue with the hyperlinks for some flex display graphs in the IFs web version not being stable. In the past, I have hyperlinked to these forecasts when writing articles (e.g., "forecasts of the Global Power Index" hyperlink in this article: https://warontherocks.com/2019/04/preparing-for-chinas-rapid-rise-and-decline/). If I only display countries in the line graph, then the link appears to be stable (this example has been stable for 2 years. However, if I try to display a country and a country group (e.g., USA, China, NATO), then the link is unstable and stops working when I send it to others.

As a related issue that I don't understand but which Cory mentioned when I told him about this link issue recently, apparently the form of the hyperlinks is unsecure and should be changed. Here's an example (hyperlink from the article mentioned above) http://www.ifs.du.edu/IFs/frm_GraphicalDisplay/%22Power%20Measure%2c%20Global%20Power%20Index%2c%20History%20and%20Forecast%22/True/4/33%2c73%2c178/1/2100.

Thanks for checking this out!
Collin

**Comment by PardeeCenterIFs** [comment]
I don't think we had tested this feature with a mix of countries and groups, I have now fixed it and put it on the web server.
