### ISSUE TITLE
IFs.NET map does not appear and keeps loading

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#4]
Date found: 10/18/20
IFs Version: 7.56 .Net Install
Found by: Luis Montes
Error Type: Display Issue
Description: The map keeps loading after opening the application
Step to replicate: Only click on the application
Reproducible in VB6 (Y/N): N/A
[IFs.NET.Map.Display.docx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/6093536/IFs.NET.Map.Display.docx)

**Comment by PardeeCenterIFs** [comment]
Couldn't reproduce this one
