### ISSUE TITLE
Estimation options in Flex Display

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#40]
Flex Display form allows two types of estimations to fill in historical data. The corresponding menu options (image pasted below) are difficult to interpret. Captions for those two menus can be either supplemented by a somewhat more detail "Help" text, or by better descriptions, e.g. "Estimate all points (regression)" for the first one and "Estimate in-between points (interpolation)" for the second one.

![Estimation Menu](https://user-images.githubusercontent.com/53452620/113799601-3899c200-970a-11eb-9ed8-0f6009ba6278.JPG)

**Comment by PardeeCenterIFs** [comment]
Help GUI will be updated soon by the resource team

**Comment by PardeeCenterIFs** [comment]
The first option does NOT use regression, it uses both interpolation and extrapolation, and that's why the second one explicitly says no extrapolation.

I'm adding Mark so this is considered when updating the help system for the GUI.
