### ISSUE TITLE
SDG Overview 'Select Year' changes with model base

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#42]
**Short Description**: The 'Select Year' in the SDG Overview Table defaults to 2032 in the 2017 rebase.
**Date found**: 04/09/21
**IFs Version**: 7.65 VB6 Install and Development
**Found by**: Jonathan David Moyer, PhD
**Error Type**: Intended application
**Description**: Upon opening the SDG Overview Table, the 'Select Year' defaults to 2032 when the model has a 2017 Base. Column headers still read "2030". 
**Steps to Replicate**: In a rebased (non-2015) version of IFs open the SDG Overview Table
**Screenshot**:
![image](https://user-images.githubusercontent.com/12075041/114217489-3caa2780-9936-11eb-9458-48881341631a.png)

**Comment by PardeeCenterIFs** [comment]
I have fixed this issue, and it will be included in version 7.66
