### ISSUE TITLE
Remittances do not impact household income

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#49]
**Short Description:** Increasing remittance inflows does not seem to impact household income (HHINC)

**Date found:** 05/07/21

**IFs Version:** 7.66 VB6 Install

**Found by:** David Bohl

**Error Type:** Model dynamics

**Description:** In a scenario which increases remittance inflows, disposable household income (HHINCDIS) increases, but household income (HHINC) and household consumption (C) remains relatively unchanged (change is negligible). This means that increasing remittance inflows does nothing to impact poverty.
 
**Steps to Replicate:**
1. Run a scenario that increases _xworkremitinm_
2. Compare XWORKREMIT, HHINCDIS, HHINC, and C between the scenario and the Base

**Comment by dkbohl** [comment]
Learned from Barry today. Remittances are not intended to pass through to HHINC, but instead to HHINCDIS. HHINCDIS is then distributed across household savings and consumption. The issue that we are seeing in Yemen is that this increase in remittances is passing through almost entirely to savings, and therefore having no impact on poverty.

Barry is looking into this via his update of the Economics Model documentation.

**Comment by PardeeCenterIFs** [comment]
Barry made some changes, included in 7.67 IP1, and I think these issues have been adressed, I tried it with El Salvador, ramping up the multiplier to 1.1 in 10 years:

![HHINCDIS_El Salvador](https://user-images.githubusercontent.com/33665510/119877163-e98c3400-bee5-11eb-9be6-11a738987432.jpg)

![C_El Salvador](https://user-images.githubusercontent.com/33665510/119877195-f1e46f00-bee5-11eb-8a64-e40b005d6685.jpg)

**Comment by dkbohl** [comment]
I see a similar impact for Yemen. There is still not complete passthrough of remittances to consumption, but a significant portion does make it. I will check it again in 7.67IP2 (rebased for the Yemen project), but think this is probably sufficient for our purposes. Thanks both!
