### ISSUE TITLE
Flex display and Self Managed Mismatch

### ISSUE THREAD

**Issue by lpicci96** [PardeeCenterDU/IFs-Issues-Tracking#53]
Creating tables for the same variable (Female labor force participation rate) in flex displays and self managed display generates idential data values, but the years do not match. See screenshots below.

VB6 7.66

In Flex displays: Set "Use all available historical data", select variable "Labor Participation Rate, History and Forecast" and "Female" in second dimention. Geography: "Liberia"

In Self Managed: Set "Historical plus Forecast" in 'Variable Selection Options". Select variable "LABPARR" for "Liberia" for "Female" then create the table

Flex Display Table:
![image](https://user-images.githubusercontent.com/56567716/118696688-ca95ef80-b7cb-11eb-84d7-eb784b2cc5e7.png)

Self Managed Display:
![image](https://user-images.githubusercontent.com/56567716/118696903-ffa24200-b7cb-11eb-805e-80ce3fff77e6.png)

**Comment by lpicci96** [comment]
It seems that Flex displays is showing the correct values/years according to IFsHistSeries

**Comment by PardeeCenterIFs** [comment]
JRS: This has been fixed, and it will be included in version 7.67
