### ISSUE TITLE
Growth accounting display: factor contributions to growth do not sum to GDPR

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#54]
**Short description:** Contributions to growth from labor, capital, and MFP do not sum to annual growth rates.

**Date found:** 05/26/21

**IFs version:** 7.67 VB6 Development

**Found by:** David Bohl

**Error Type:** Model dynamics

**Description:** In the growth accounting display, contributions to growth from labor, capital, and MFP do not sum to annual growth rates. This is expected (and noted) in years where IFs uses exogenous growth rates, but should not be the case for subsequent years.

**Steps to replicate:**
1. Open up the growth accounting display
2. Select any country
3. Select _Capital_, _Labor_, _MFP_, and _GDP Growth (for comparison)_
4. Make a table
5. Compare the sum of  _Capital_, _Labor_, and _MFP_ with _GDP Growth (for comparison)_

**Screenshots:**
![image](https://user-images.githubusercontent.com/12075041/119714865-5b567600-be31-11eb-9beb-116147ef687b.png)

**Excel example:**
[GrowthAccountingExample.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/6549034/GrowthAccountingExample.xlsx)

**Comment by PardeeCenterIFs** [comment]
In the explanatory note Barry says: "Thereafter (after the exogenous years) the sums of capital, labor, MFP (multifactor productivity), and capacity use (utilization) should sum quite closely to the value added (VADD) growth for the sectors that IFs represents only in value terms in its computable general equilibrium model system (those sectors other than agriculture and energy)".

So there are 2 issues not considered here:

1. You're missing Capacity use (CAPUT).
2. The Agriculture and Energy sectors will be off, and can explain some of the total difference.
