### ISSUE TITLE
South Sudan GDPR, 2030s - 2040s

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#57]
Short Description: Strange GDPR in South Sudan 

Date found: 05/10/21

IFs Version: 7.67 VB6 Development

Found by: Willem Verhagen

Error Type: Model dynamics

Description: The 2030s and 2040s are a strange time for Base Case forecasts of GDPR for South Sudan.

Steps to Replicate: Draw GDPR

Screenshot: 
![image](https://user-images.githubusercontent.com/12075041/121625778-260d7300-ca42-11eb-9f01-7f95ee322756.png)

**Comment by dkbohl** [comment]
May start off as a CAPUT issue, then MFP in early 2040s:
![image](https://user-images.githubusercontent.com/12075041/121626247-15113180-ca43-11eb-8c7f-6b310b14dab4.png)

**Comment by PardeeCenterIFs** [comment]
![GDPR South Sudan](https://user-images.githubusercontent.com/33665510/133526515-fbbe91c9-954e-4518-9ca3-36b154e74399.jpg)

I think this issue has been solved in version 7.74, and probably even earlier with changes made to the initialization of igdpr for version 7.71, Barry also worked on oscillation issues on GDPR in version 7.72.
