### ISSUE TITLE
One-button re-basing

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#63]
We should be able to rebase the model to any year with one option that changes ifsinit, pulls population data, adjusts most recent data, reruns the preprocesser, then rebuilds the base.

**Comment by PardeeCenterIFs** [comment]
I have completed this option, it'll be at the end of the Extended Features menu in Development mode only, named: "Guided Base Year Change" and it will be included in version 7.71.
