### ISSUE TITLE
One common feature used for tables not included in IFs

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#64]
Comparison Options within Tables is a very useful feature of the model that is widely used.  But there are many instances where we take data from IFs and put it in Excel to do more detailed comparisons that you cannot do in IFs.  I would like to add the ability to do a comparison that subtracts and divides Column A with every other column in a table.

For example, if you have one scenario and you want to compare how every other scenario differs from that one baseline (a very standard comparison) you could first select the comparison scenario, and then select as many other scenarios as you would like.  So, Column A would be the comparison scenario and columns b...n would be the things to compare.  So if you choose this Table option it would either subtract or divide Column A with Column B...N for one unit, then move to the next unit.  It would be good to have four versions of this...

Group Ratio Comparison (a/(b...n))
Group Ratio Comparison ((b...n)/a)
Group Difference Comparison (a-(b...n))
Group Difference Comparison ((b...n)-a)

**Comment by Coryv221** [comment]
Code implemented for scenario comparison

But now we need to add a "generalized function" that doesn't break up by scenario but instead does A/(b.....n) regardless of scenarios

**Comment by Coryv221** [comment]
Full implementation done in VB6 and .NET, should be both upcoming consolidations, as of writing

**Comment by jonathandmoyer** [comment]
Thank yo8u
-----
  Jonathan D Moyer, PhD
  Assistant Professor
  Director
  Frederick S. Pardee Center for International Futures
  Josef Korbel School of International Studies
  University of Denver
