### ISSUE TITLE
Default name for saving working file

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#66]

**Comment by mtirfan66** [comment]
When a scenario file with a name is brought in to the tree, the save working file option should bring that filename as the default name for the .run.

![image](https://user-images.githubusercontent.com/53452620/123883312-9dc21580-d8fd-11eb-8528-c1f6ea027310.png)

**Comment by PardeeCenterIFs** [comment]
This has been implemented and it will be included in version 7.79.
