### ISSUE TITLE
Power function of scatter plot giving an error under self-managed display

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#7]
Error short description/title: Power function of scatter plot giving an error under self-managed display
Date found: 11/23/2020
IFs Version (number, VB6/.NET, Install/Development): IFs 7.56 .NET install
Person found by: Suraj Thapa
Type of error (see below): Display issues
Description of error: The options called “Power” under Analysis of Scatter plot is giving an error. They give an error called “Error Handler for IFsWeb.” Steps to replicate the error, if applicable: Using Pardee wiki - link – do as it says about scatter plots for self-managed display –

Go to Self-Managed display. 2. Select country/regions, any variable (I chose GDPPCP and TFR), and just base working model, then go to display 3. Choose all county and go to display 4. Go to Graph Tab and then to the "Scatter Plot" 5. Go to Analysis and then "Relationships" 6. Go to "Power" function. We end up with an error called “Error Handler for IFsWeb”
Attempt to recreate error in VB6 or .NET depending on where found and note whether error reproducible: It was on windows and .NET

**Comment by PardeeCenterIFs** [comment]
JRS: This was fixed by Cory and the fix will be included in version 7.66, compilations options needed to be explicit in configuration file.
