### ISSUE TITLE
Update Relative Risk factors for Child Stunting

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#75]
As discussed today (2021/07/28) with Yutang and Jose we want to link child stunting to relative risk factors for diseases based on IHME data. This project consist of two necessary steps, and one optional step

1) Provide an updated RR table to Jose, with the addition of RRs per disease category for child stunting (HLSTUNTCHL). The RRs need to disintguish between 0-1 and 1-4 year olds. We want to only take values from < -2 standard deviations (assigned to Yutang/data team)
2) Update the code to link the rr tables and child stunting projections, primarily challenge will be to aggregate the different values below -2 standard deviations

A third optional venue is to:
3) update the entire RR tables based on the most recent IHME data. We should this, but the reason it is listed as optional is because this is a much bigger undertaking in which we need to understand how the new data of IHME map to the disease category (mappping table) and then either write a pre-processor or update the code to integrate all new categories into the 15 disease categories from IFs. 
We decided to discuss this issue more broadly in the modelling pod

**Comment by quciet** [comment]
![rr table](https://user-images.githubusercontent.com/34465524/127935119-0316a54b-04ad-4294-a90d-220c125f5555.png)
I've added those 6 entries into the table HealthProxDrivRRs in IFs.mdb. José should be able to handle this from the code now. Let me know if there is any additional step needed.

**Comment by wverhagen** [comment]
Jose could you confirm that the update has been implemented and that we can close this comment

**Comment by PardeeCenterIFs** [comment]
This was included in version 7.73 which was created on August 20th, you need to turn on the switch hlstuntchlsw=1 to use it.
