### ISSUE TITLE
SSP scenario update in scenario tree gives message that "nothing has changed"

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#77]
There is a small issue in the scenario tree builder with SSP scenarios.
There are two scenario parameters for that: ifsexomodelid is assigned a value of 1-5 representing the SSPs.
The most simple way to change SSPs all at once is to make a scenario of SSP 1. Save that. And then change ifsexomodelid to 2 to switch to SSP2.

However, if you do so in the scenario tree and name and save scenario it gives the warning:
Are you sure you want to save, nothing has changed

You can still save it afterwards, but clearly something has changed so this message should not pop up.

Replication. First create a SSP1 scenario. Save. Then have scenario in scenario tree. Change to SSP2 and save again. 

IFs version 7.70 vb6.

![image](https://user-images.githubusercontent.com/18350553/128248634-30618c92-48e8-4811-b1f3-6775155ff40c.png)

**Comment by PardeeCenterIFs** [comment]
I tried these steps:

1. Open the Scenario Tree.
2. Search for ifsexomodelid.
3. Load it.
4. Set it to 1.
5. Save the scenario file.
6. Change the value of ifsexomodelid to 2.
7. Save the scenario file with a different name.

Didn't get any popup messages saying nothing change.
