### ISSUE TITLE
Spelling Error in SDG Graph 

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#78]
The Global Summary option in the SDG Graph menu is missing an m, currently reads "Global Sumary". 
Date Found 8/3/2021
IFs 7.70
Found by Audrey Pirzadeh

![image](https://user-images.githubusercontent.com/83729959/128276812-7566443d-fd5f-46bd-875f-41c7d8e89e34.png)

**Comment by Coryv221** [comment]
Will be in 7.72
