### ISSUE TITLE
Power Contribution Display Error

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#79]
Nothing is populating for the Power Contribution page in IFs 7.70. 
Date Found: 8/4/2021
Found by Audrey Pirzadeh
![image](https://user-images.githubusercontent.com/83729959/128277609-b0c85f13-3050-4d38-b2d3-626322031256.png)

**Comment by PardeeCenterIFs** [comment]
José: I can't reproduce this one, it seems to be working in version 7.71.

**Comment by PardeeCenterIFs** [comment]
José: I'm closing this since during the modeling Pod Audry mentioned it wasn't a problem anymore, tested in version 7.72.
