### ISSUE TITLE
.NET SSP Scenario Error

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#80]
While trying to run the SSP5 scenario in the .NET version of IFs the error "Bahamas is not a valid group" popped up, then IFs crashed.
Date Found: 8/5/2021
Found by: Resource Team

**Comment by PardeeCenterIFs** [comment]
I couldn't reproduce this issue, I tried on my 7.73 + Development changes version, maybe need to try again when version 7.74 is ready.
