### ISSUE TITLE
Update CLPCCVR and GINIDOMR

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#81]
Currently we have the ability to set gini (inc inequality) and clpccv (food inequality) at the same level as the base year (ginidomr=1).
However, we would want to update the functionality so that:
- we can put both values stable relative to last year values
- in other words a value of 1 in 2020 would freeze it at the 2019 value
- this probably requires the use of a saved variable in the code

Assigned to Jose

**Comment by wverhagen** [comment]
Jose could you confirm whether 7.73 includes a change to the behavior of ginidomr and clpccvr. or whether it is still an open issue?

**Comment by PardeeCenterIFs** [comment]
We decided to create a new parameter for this, the existing ginidomr is used as a multiplier of the initial condition:

GINIDOM(R%) = GINIDomI(R%) * ginidomr(R%)

The new switch will allow you to freeze GINIDOM in mid-horizon, 2020 for example:

        If ginidomcnstsw(R%) = 1 Then GINIDOM(R%) = sGINIDOM(R%)

**Comment by PardeeCenterIFs** [comment]
Regarding clpccvr, when we set it to 1, then it freezes it at any time in the horizon.
