### ISSUE TITLE
Normalization of Influence series

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#86]
The normalizations of _Influence_, _Dependence_, and _Bandwidth_ are done in a two-step way in the code. First, an LoR-based normalization is applied. Then, a min-max normalization. There are two potential concerns with the current implementation. 

First, and most pressing, the min and max used to calculate the normalization are identified based on the current year. This contrasts with the historical data where it is calculated using the min and max values from the entire 1960 to 2018 window from all dyads. Second, the LoR-based normalization appears to be an unnecessary step as it functionally multiplies by a constant just before the min-max normalization.

To address these, we should first consider switching to using the same fixed min and max values as the historical data. This will lead to having potential values greater than 1 in the forecasted series, however, it will also ensure comparability to the historical data. Second, we should remove the LoR-based normalization of _Influence_, _Dependence_, and _Bandwidth_ directly preceding the min-max normalization.

**Comment by PardeeCenterIFs** [comment]
The process to find Minimum and Maximum takes a long time, and in all 3 cases it returned 0 and 1 respectively, so it was much more efficient to simply set those min and max values as a constant across time.
 I also removed the LoR normalization.
Changes will be included in version 7.81

**Comment by caleb-petry** [comment]
The min and max values should be constant values based on the unnormalized values from the historical data. Given what you said here, the historical series are likely the normalized versions. 

I'll take another look at the code and data/reports then circle back with the current values and suggestions on how to implement them to bring the forecasts more in line with other uses.

**Comment by caleb-petry** [comment]
This was implemented in a previous version.
