### ISSUE TITLE
Create and Initialize Trade Agreements Variable

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#87]
At present, there does not appear to be a _Trade Agreement_ forecast. There does appear to be a placeholder (_tradeagreementindex_) in the Influence-specific code already. 

To initially address this, we should initialize the forecast series from data (_TradeIndex_ is the historical series) and hold it constant, and then replace the placeholder with this new series. Additionally, we should add an additive parameter to allow for changes in scenarios.

**Comment by PardeeCenterIFs** [comment]
I have completed the creation and initialization of DYADTRADEAGREEMENTINDEX, it should be included in version 7.81.

**Comment by caleb-petry** [comment]
@solox1, please add an additive parameter "dyadtradeagreementindexadd". Thanks!

**Comment by PardeeCenterIFs** [comment]
I have added the parameter and it will be included in version 7.82
