### ISSUE TITLE
Forecasting Alliances and Level of Representation

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#88]
The current forecasts of _Alliances_ and _Level of Representation_ (LoR) grow based on the growth of monadic LoR (averaged with treaty’s monadic growth for Alliances) for the given actor. As an example, say the United States experiences an increase of 10% in their monadic LoR in a given year. The _LoR_ forecast would increase in value by 10% in each United States-Partner dyad. This also leads to values greater than the indexes’ maximum values. Currently, all zero values stay at zero. 

To initially address this, we should initialize these forecasts from data and hold them constant in the forecast. Additionally, we should add additive parameters to allow changes in scenarios.  Concerning _LoR_, these changes will remove the link to the monadic forecast. It may be appropriate to implement hard min and max values as well based on their indexes.

-------------------------
While not included in FBIC, we may wish to also change the dyadic _Treaty_ forecasts as well. At present, it uses the same forecast logic as these two.

**Comment by PardeeCenterIFs** [comment]
Alliances is already being initialized from data: SeriesDiploAllianceSharedWeighted_ATOP
LOR is being initalized from: SeriesDiploEmbassyOut

**Comment by PardeeCenterIFs** [comment]
I have made the changes to the code to keep ALLIANCES and LOR constant, regarding adding additve parameters, can you confirm we really need them given that we already have multiplicative ones?

**Comment by caleb-petry** [comment]
Sorry for the delay. Correct, we do need the additive parameters as there are a significant amount of zeros in both series.

**Comment by PardeeCenterIFs** [comment]
I have now added parameters dyadallianceadd and dyadloradd, they should be included in version 7.82, remember to re-download the bilateral files from ifs02.
