### ISSUE TITLE
Time tab of Radial Chart under self-managed display not working

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#9]
Error short description/title: Time tab of Radial Chart under self-managed display not working
Date found: 12/1/2020
IFs Version (number, VB6/.NET, Install/Development): IFs 7.56 .NET install
Person found by: Suraj Thapa
Type of error (see below): Display issues
Description of error: The time (advance or regress) tab of under graph tab (which is under self-managed display) is not working. Steps to replicate the error, if applicable: Using Pardee wiki - link – do as it says about "Radial Chart" for self-managed display –

Go to Self-Managed display. 2. Select country/regions, any three variable (I chose GOVINDSECUR, GOVINDCAPAC, and GOVINDINCLUS), and just base working model, then go to display 3. Go to Graph Tab and then to the "Radial Chart" 4. Go to Time and then "advance" or "regress" or "Go To Year" 6. We end up the same time period
Attempt to recreate error in VB6 or .NET depending on where found and note whether error reproducible: It was on windows and .NET

**Comment by PardeeCenterIFs** [comment]
This one was fixed in version 7.63 by José
