### ISSUE TITLE
Common block change, to elasticities of food demand to price

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#95]
Hi Jose, could we make the parameters elascd, elasmd and elasfd not global parameters but country and region specific. 

Basically I want to run a scenario for a scientific article in which I change price elasticities using the below table (cereals for crops, meat for meat, fish for fish)

![image](https://user-images.githubusercontent.com/18350553/137040417-f2e78a75-da67-40ae-92a5-0aec2d6d1ced.png)

**Comment by PardeeCenterIFs** [comment]
I have now made the change in dimensions to these 3 parameters, and they should be included in version 7.79.
