### ISSUE TITLE
data importing process still uses the old country names

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#98]
The data import process is still using old country names. Once the data is imported, it will then be converted to new country names, which means I'm still maintaining 2 lists of country names.

**Comment by mtirfan66** [comment]
I have compared the country column in the "Country Translation" table in IFs.MDB with the same in the some (new and older) series in IFsHistSeries. I see them to be same. If those columnd match, imports should have same country names
Now newly imported series could have been fixed by you, Yutang. I am not sure.
I can import a table and check myself. I need to know two things though -
a. Please let me know which IFsHisSeries table's (any?) country column the imported data should match?
b. If you have an Excel with a botched imported Access table, please send me both. Let me know which country translation column you have used.

Thank you.
-Mohammod

**Comment by quciet** [comment]
> I have compared the country column in the "Country Translation" table in IFs.MDB with the same in the some (new and older) series in IFsHistSeries. I see them to be same. If those columnd match, imports should have same country names Now newly imported series could have been fixed by you, Yutang. I am not sure. I can import a table and check myself. I need to know two things though - a. Please let me know which IFsHisSeries table's (any?) country column the imported data should match? b. If you have an Excel with a botched imported Access table, please send me both. Let me know which country translation column you have used.
> 
> Thank you. -Mohammod

Thanks so much for your prompt reply Mohammod. Please see below for a step-by-step replication of the problem.

First, I can confirm that the __Country Translation__ table in the IFs.mdb has the newest country names, e.g., __United States of America__ (we used to use __United States__), see a screenshot below.

![image](https://user-images.githubusercontent.com/34465524/137551067-daedf662-96cf-4bf5-a6e2-92161a52ef94.png)

To simplify the illustration, I created a dataset, with only two records, one with the new country name, and the other one with the old name, see below

![image](https://user-images.githubusercontent.com/34465524/137551226-e1479125-dfbe-4eba-b581-8a88af9708f9.png)

If the importing process is working correctly (with the correct importing steps assumed), then IFs should capture the value __7788__ from the row  __United States of America__. So I gave it a try through the *Extended Features*, see the picture below and please let me know if I'm making any mistakes at this importing process.

![image](https://user-images.githubusercontent.com/34465524/137551467-e2dae9f9-2b41-4087-be40-d2c52898aa8f.png)

Then I hit the *Import* button and checked the pop-up window. It can be seen that imported value is, instead, __5566__ from the record of __United States__ in the raw data.

![image](https://user-images.githubusercontent.com/34465524/137551640-5066482a-4bb5-4153-966f-b776ae76de57.png)

To double-check, I then hit the *View Excluded* button, and confirmed that the record with the new country name has been excluded. 

![image](https://user-images.githubusercontent.com/34465524/137552061-f454c387-4bd0-491b-a7cb-ac1f839fe194.png)

Perhaps I did something wrong in the data importing process, if not, please give it another look at the code and let me know if this can be directly fixed through the code or data side. 

I'm lowering this task to priority 3 because currently, I'm asking all the RAs to import data using the old country names for country concordance as a turnaround. And I realize that your work with the poverty stuff is much more important. So take a look whenever you have time and keep me posted. Thank you so much!!!
